### ISSUE TITLE
Update adaptors docs string 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#165]
### Description 
Adaptors doc string are not properly maintained and need to be updated to have the right `jsdoc` tags and include examples for each helper function

| Active Adaptors | Other Adaptors |
| --------------- | -------------- |
| asana           | beyonic        |
| postgresql      | fhir           |
| primero         | bigquery       |
| sftp            | openhim        |
| msgraph         | rapidpro       |
| mysql           | dynamics       |
| mssql           | cartodb        |
| dhis2           | facebook       |
| salesforce      | godata         |
| googlesheets    | khanacademy    |
| http            | magpi          |
| commcare        | progres        |
| mailchimp       | maximo         |
| kobotoolbox     | medicmobile    |
| openmrs         | mogli          |
| openspp         | nexmo          |
| surveycto       | mongodb        |
| ocl             | resourcemap    |
| openfn          | smpp           |
| mailgun         | telerivet      |
| common        | twilio      |
|                 | vtiger      |
|                 | zoho      |

**Comment by mtuchi** [comment]
We should break this down into smaller issues that are adaptor specific. That way it will lighten the load and make it easy to prioritize. Here is our starting point https://github.com/OpenFn/docs/issues/417

**Comment by mtuchi** [comment]
I think we should close this issue and pickup our top 5 adaptor to start with 
cc @aleksa-krolls @josephjclark any thoughts ?

**Comment by josephjclark** [comment]
Sure - do we know what the top 5 is yet?

Do we have a clear spec for what the docs should look like?

I suggest we don't take action until we can answer those two questions... maybe we need to pick up that common issue first

**Comment by josephjclark** [comment]
I am going to close this issue down: we've broken out the top 5 into separate stories, and besides we've done a lot of docs work over the last six months
