### ISSUE TITLE
Adaptors tests

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#167]
### Description
During the process of migration, we skipped a lot of tests that are failing. We should have a tests mock framework to make the process of writing test easy in adaptors.

Currently most of the tests in adaptors are quite similar, and this doesn't seem quite right, because the way an adaptor is being tested depends on the system that adaptor is for. For example if the adaptor is for a REST API then maybe mocking with libs like `sinon` is the way to go but if the adaptor is for a database then we should have defined database sandboxes to do integration tests, etc.

There are also some helper functions that are being re-tested like `execute` while they have already been tested in another adaptor.

@taylordowns2000 we do think that there should be an interesting discussion around the way adaptors are being tested currently and maybe an outcome of that discussion will be defining patterns, tools, strategies, ..., for testing adaptors.

**Comment by taylordowns2000** [comment]
I'd say we want to have a separate PASS/FAIL status for each adaptor in the `/packages` directory. From a CI perspetive, this might mean that we configure circle to recurse through all directories inside `/packages` and run `pnpm test` for each, outputting the results individually.

**Comment by mtuchi** [comment]
I think we should close this and create issues for individual adaptors [Preferably our top 5 adaptors]. This might be a good transition to testing [mockable operations](https://github.com/OpenFn/adaptors/pull/482)  
cc @josephjclark

**Comment by josephjclark** [comment]
Yeah I kinda agre

I think the mockable operations stuff needs to happen first and we don't really have an issue for it.

We already have issue for some problematic tests.

I don't think this issue has intrinisic value, but I don't think we should create new issues unless we absolutely need it.

Maybe when the mocking stuff is done and merged, we can raise  some `good first issue` tickets to expand the tests on the top 5. But let's not bother for now.
