### ISSUE TITLE
Salesforce: typings are all wrong

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#184]
In salesforce, pretty much every  operation is exported as type `any`, which is useless when trying to do any analysis!

The problem I think comes because every operation is wrapped in `lodash.curry`, which we have no types for in the repo.

**Comment by josephjclark** [comment]
A couple of other issues here:

* `FakeAdaptor` is exported from `index.js` - but why? It's only used for unit tests and shouldn't be a public export
* Everyting is marked with `@constructor`, which is mostly harmless but is very misleading

**Comment by josephjclark** [comment]
The typing issue is just the same as #16. The library types of `lodash` and `axios` don't get written to the DTS - not even as like an import. This does need resolving.

**Comment by josephjclark** [comment]
So this is a bit arbitrary, but after hours of experimentation, this seems to be the answer.

Here's what we have now:
```
// Adaptor.js
import lodash from 'lodash'
const { curry } = lodash;

export function describe = curry(...);

// Adaptor.d.ts
export const describe: any;
```

And here's the best solution I've found:

```
// Adaptor.js
import { curry }  from 'lodash'

export function describe = curry(...);

// Adaptor.d.ts
export const describe: import("lodash").CurriedFunction1<any, any>;
```

Do I like it? No. Does it work? Well, also no actually - because a) the syntax blows up unit tests and b) the typing betrays almost none of the semantics of the function. But it's a little bit better than any.

Now, this goes away when we re-write the adaptor in TypeScript. We could also, I suppose, hand write the DTS in difficultcases like this.s

**Comment by josephjclark** [comment]
Another swing at this is to override the definition of lodash.curry and treat it as a sort of proxy:

```
// Adaptor.js
/// <reference path="./overrides.d.ts" />
...

// Adaptor.d.ts
declare module "lodash" {
  export const curry: <F>(fn: F) => F;

  export default {
    curry,
  };
}
```

This almost works! The generated signature looks correct - the problem is that the comments in the JS are lost, so we lose all the documentation. Basically when the generic type is returned, TS "exports" the docs associated with that inner function.

This does work though:

```
// Adaptor.js

/// <reference path="./overrides.d.ts" />
import _ from "lodash";
const { curry, flatten } = _;

/**
 * My function
 */
const _curried1 = (x) => x;
export const curried1 = curry(_curried1);

// Adaptor.d.ts
/**
 * My function
 */
export function curried1(x: any): any;
```

In other words, restructuring the adaptor in a slightly weird way would help the DTS definitions,

**Comment by stuartc** [comment]
@josephjclark this is done right?
