### ISSUE TITLE
Publish docs

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#22]
We need to generate and post docs somewhere.

I think this is a githib actions thing - we should add an action to build docs and publish them to github.io.

We can probably then exclude docs from the standard build command.

**Comment by taylordowns2000** [comment]
@josephjclark , more thoughts on docs from Aleksa:

currently documentation for adaptors lives in two places:

1. https://docs.openfn.org/documentation/apps/dhis2
2. https://openfn.github.io/language-dhis2/

if we're generating docs here using something like docusaurus, could/should we subsume those "apps" pages on docs.openfn.org into the adaptors documentation here? i'm imagining a structure like this getting published:

```md
README.md # comes from existing /adapors/dhis2/readme.md -> turns into landing page
PLATFORM-USAGE.md # comes from existing docs.openfn.org/documentation/apps/dhis2 -> turns into page that sits next to landing page
docs/ # all the JsDoc/TsDoc stuff is built here
```

Alternatively, we could combine README.md and PLATFORM-USAGE.md, but I think separate is better as the first is aimed at adaptor developers and the second is aimed at platform users. Thoughts?

cc @stuartc , @mtuchi 

**🎯 STRETCH GOAL 🎯** - _How do we create a docs build for **each version** that's published to npm?_

**Comment by taylordowns2000** [comment]
@mtuchi , this issue should now be focused on the yellow box... a github action which builds and commits the docs to the `docs` branch

 ![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/f6cfc25a-cef4-4b36-adbd-42714bafbe1f)
