### ISSUE TITLE
Build optimized docs template for Docusaurus

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#228]
@taylordowns2000 commented on [Tue Nov 01 2022](https://github.com/OpenFn/docs/issues/332)

## Note
the new doc strings that were introduced for #228 don't work with docusaurus: https://github.com/OpenFn/docs/actions/runs/4644501002/jobs/8219812508

Please update them and test them with your local docusaurus build before opening a PR fix.

To test to, put the generated docs JSON from this repo into your docusaurus build file here: https://github.com/OpenFn/docs/blob/main/generate-adaptors/index.js#L190

## Original issue

Once we've got the `adaptors` -> `docs` documentation build down, we should optimize the documentation that gets written by using:

1. A guide to cherrypicking and styling docs from `jsdoc2md`: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Cherry-picking-which-documentation-appears-in-output
2. The documentation style guide from [docs.openfn.org](https://docs.openfn.org/documentation/style-guide/) (see [source here](https://github.com/OpenFn/docs/blob/main/docs/style-guide.md).)

## Deliverables for this issue

- [x] Mark execute as private in docs
- [x] Sort docs alphabetically
- [x] Template the right-hand side menu of the adaptor docs, to only show the function name and not the whole signature

---

@mtuchi commented on [Tue Jan 17 2023](https://github.com/OpenFn/docs/issues/332#issuecomment-1449622985)

@mtuchi template the right hand side menu of the adaptor docs, to only show the function name and not the whole signature
![Screenshot from 2023-01-17 14-52-28.png](https://images.zenhubusercontent.com/6310851c29415866ce13fb98/560b2ffe-2d38-4d0f-a4ac-65491ba6c587) 

---

@mtuchi commented on [Wed Mar 29 2023](https://github.com/OpenFn/docs/issues/332#issuecomment-1488010322)

Top 3 implementation planning 
- [ ] Mark execute as `private` in docs 
- [ ] Sort docs alphabetically
- [ ] Template the right-hand side menu of the adaptor docs, to only show the function name and not the whole signature
cc @taylordowns2000

**Comment by taylordowns2000** [comment]
dropping the `gfm: false` flag for jsdoc-2-markdown fixed this! looking good: http://localhost:3000/adaptors/packages/primero-docs
