### ISSUE TITLE
Update adaptors using `request` dependency  to `superagent`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#236]
### Description
Some of our adaptors are using the `request` package which is being deprecated Since Feb 11th, 2020, [See the deprecation warning ](https://www.npmjs.com/package/request) and [a GitHub issue for a reason why the package is deprecated](https://github.com/request/request/issues/3142). We should update the adaptors that are using `request` to use `superagent` instead since we are already using [superagent](https://www.npmjs.com/package/superagent) in most of our adaptors.

### Adaptors list
- [ ] mssql
- [ ] dynamics
- [ ] facebook
- [ ] http
- [ ] khanacademy
- [ ] magpi
- [ ] maximo
- [ ] medicmobile
- [ ] mogli
- [ ] openmrs
- [ ] primero
- [ ] resourcemap
- [ ] smpp
- [ ] surveycto
- [ ] vtiger

## Security Alerts

There are now security alerts associated with this issue - quite scary really although I doubt they're a concern to our adaptors.

* https://github.com/OpenFn/adaptors/security/dependabot/59
* https://github.com/OpenFn/adaptors/security/dependabot/56
* https://github.com/OpenFn/adaptors/security/dependabot/19 (all affected versions I think come from superagent)
* https://github.com/OpenFn/adaptors/security/dependabot/32

**Comment by josephjclark** [comment]
There are now security alerts associated with this - it's more important than ever that we remove `request` from this repo.

The upcoming `unidici` migration will solve this.

I've updated the original issue with references to the security alerts.

**Comment by josephjclark** [comment]
I've closed this down in favour of:

https://github.com/OpenFn/adaptors/issues/547
https://github.com/OpenFn/adaptors/issues/548
https://github.com/OpenFn/adaptors/issues/549
