### ISSUE TITLE
Update the adaptors template

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/adaptors#250]
Update the [adaptors template](https://github.com/OpenFn/adaptors/tree/dab11c0845c1affb01e822ed44494906dde1fc09/packages/template)

- leave the tests folder emtpy (and add to readme to explain how to write them)  
- change the template so that it's not using requests -> can we use common instead? - use axios instead of jsfetch? 
- remove lib directory? 
- Update readme with instructions -> guidelines and links to test examples from other adaptors for proper integration tests
- check package.json?

**Comment by josephjclark** [comment]
This is basically all done (especially since merging the readme last week).
