### ISSUE TITLE
`sftp` `common` Add support for csv parsing 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#252]
### Description

Add helper function in `common` adaptor for parsing csv files, 

```
// Notes from Stu
// Takes a stream, returns an Object[]
parseCSV(stream|arraybuffer, parsingOptions = {}) 
// Not exported for now
streamCSV(fileStream, parsingOptions = {})
```

In `sftp` adaptor create a `readFile` or `getFile` helper function that will use `csv.parse` from `common` for parsing the csv file stream 

```
// uses the helpers but provides a higher level interface
loadFile(filePath, parsingOptions = {parser: (true|false|'json'|'csv')})(state)  or
getFile(filePath, parsingOptions = {parser: (true|false|'json'|'csv')})(state)
```

Related issues #251 #182 

Use csvtojson package - https://github.com/Keyang/node-csvtojson#parameters

**Comment by mtuchi** [comment]
To address `parseCSV()` in `http` and `bigquery` https://github.com/OpenFn/adaptors/pull/256#issuecomment-1573319101
Comments from `Fri Jun 2` standup. 
We should update the `parseCSV` in `common` and export it `http` and `bigquery`

**Comment by mtuchi** [comment]
`parseCSV()` will take `csvString` or `csvStream` as the first argument, this is different from `parseCSV` in `http` and `bigquery`, which takes a `path` to the local csv file.

**Comment by josephjclark** [comment]
How do we feel about different adaptors having subtly different signatures?

Technically the signature is the same (string as the first parameter), but semantically a path and data are two very different parameters. I worry this would be confusing.

On the other hand, when using http a) the historical approach is to pass a url and b) a url is totally intuitive when you're in the http world.

So overriding the common signature to specialise a function for a particular domain probably does make sense.

We could either add an `asData` option to HTTP, if we ever wanted to pass csv data directly, or we could do something awkward like expose a `commonParseCSV` function. But we should only do either of those things when actually needed.

**Comment by mtuchi** [comment]
@josephjclark i like the `commonParseCSV` option but i hope we can come up with the better name

**Comment by mtuchi** [comment]
Closing this it's already done here https://github.com/OpenFn/adaptors/pull/287
