### ISSUE TITLE
Address open PRs in other sftp repo then archive

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/adaptors#27]
@mtuchi , there are two open PRs (and a third for the credential-schema) in https://github.com/OpenFn/language-sftp/pulls.

Let's touch base on this tomorrow—I want to archive that repo but make sure we're not missing any of your good work here in `/adaptors`

**Comment by mtuchi** [comment]
@taylordowns2000 I think we have achieved this task and archived the `sftp` repo, So I am closing this issue. 
So I am closing this issue
