### ISSUE TITLE
`msgraph` add sharepoint function

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#284]
### Description
Improve the `msgraph` to have share point functions

```
sharepoint.getSiteId(...);
sharepoint.getDriveId(...);
sharepoint.getFolderId(...);

sharepoint.getFolderItems(siteId, driveId, folderId);
each(
  '$.state.data[*]',
  get(dataValue('@microsoft.graph.downloadUrl'))
);
```
See [adaptors flexibility docs](https://docs.google.com/document/d/10HSby-q9D5YO9kDsecArMGAtyaTGAohVXMEBUgeASfo/edit) for more information

**Comment by mtuchi** [comment]
@aleksa-krolls i am opening this issue to track adding `sharepoint` specific functions
For the time being here is how you can get the `siteId, driveId, listId`

`getSiteId`. Requires `sharepointUrl` eg: `openfnorg.sharepoint.com`
- get(`/sites/${sharepointUrl}`)

`getDriveId` Requires `siteId`. The `siteId` is a result of `getSiteId`
- get(`/sites/${siteId}/drive`)

To get lists
- get(`/sites/${siteId}/lists`);

To get a specific list `get(`/sites/${siteId}/lists/{list-id}`);` or `get(`/sites/${siteId}/lists/{list-title}`);`
- get(`/sites/${siteId}/lists/Documents`); // Using list-title (displayName from lists response)

**Comment by mtuchi** [comment]
Thoughts on `getDrives()` function, from the documentation of **[Get drive](https://learn.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0&tabs=http)** . You can get drive by either `siteId`, `groupId` or `driveId`. 
below are suggestion for `getDrives()` implementation

```
// Style A
getDrives('sites', 'openfn.sharepoint.com');
getDrives('groups', 'groupId');
getDrives('drives', 'driveId');

// Style B
getDrives({ resource, resourceId });
getDrives({
  resource: 'sites',
  resourceId: 'openfn.sharepoint.com',
});

// Style C
getDrives({ siteId: 'openfn.sharepoint.com', defaultDrive: true }); // The default value for defaultDrive: false
getDrives({ driveId: 'ibasdasa' });
getDrives({ groupId: 'somegroupid' });


// Style D
getSiteDrive('siteId')
getGroupDrive('groupId')
getDrive('driveId')
```

The current implementation of `getDrive()` uses `StyleC`. @taylordowns2000 @josephjclark any suggestions on the style i should use ?

**Comment by taylordowns2000** [comment]
How are you actually using it? Right now you’re the only user, so go with
the implementation that is easiest for you to use while you’re calling this
function to write your job, but nothing more.

I say “C” if it does the trick for you now and it’s already done! We don’t
want to write code that might not be used so, the simpler the better. Once
we have use case #2 (that is to say, something other than how you’re using
it for this actual client) we can extend or refactor.

**Comment by mtuchi** [comment]
[Original comment from Joe](https://github.com/OpenFn/adaptors/pull/297#issuecomment-1640650937)

After a long call with @mtuchi I'm going to recommend more changes API (sorry!)

It's proving really tricky to map the msgraph API to a clean JS interface. We either have a million functions or a very complex, undocumentable list of arguments.

After going through some of the cases I've decided to try and raise the abstraction level. All we really want to do is get (and maybe write) a list of files from drive. The rest is all detail and boilerplate. And I think it's important that job writers can get information out of msgraph without having a PHD in their documentation.

So the new concept is basically this:

* At the top of an `msgraph` job, you 'connect' to a drive (get a reference to it). There are multiple ways you might do this. The drive reference is written to state (with an optional name so that you can connect multiple drives)
* You can use `getFile`, `writeFile` and `getFolder` with a path (and optional drive name). This will use the drive id from your state and pull file/folder contents/metadata down for you.

We're breaking for evening but right now the API looks like this:
```
// Gets a drive reference and writes to state.drives.default
// @param specifier: specify the drive to get. default 'me'.
//         If an id/owner pair, will return the default drive for the specified owner
// @param name: optional name for the drive. Will be written to state.drives[name].
getDrive(specifier, name, callback)

// Examples:
getDrive({}, 'joe');   // get my drive and name it joe
getDrive('me', 'joe');   // get my drive and name it joe
getDrive({ id: 'driveId' }, 'joe'); // Get a drive by Id
getDrive({ id: '<siteId>', owner: 'sites'}, 'joe'); // get default drive for a site
getDrive({ id: '<userId>', owner: 'users' }); // get default drive for a user

// return an array of folder contents
// We should safely URI encode the path
// Path must start with /, else will be treated as an id
// writes to state.data
// uses default drive
getFolder(pathOrId, { options }, (callback = s => s));

// return a single file's content (pass { metadata: true } to get metadata only)
// return an array of folder contents
// We should safely URI encode the path
// Path must start with /, else will be treated as an id
// writes to state.data
// uses default drive
getFile(pathOrId, { options }, callback);

// writes one or more files to the path provided
writeFiles(pathOrId, { options }, data, callback)

// loose spec for getFile/writeFiles options
const options = {
  driveName: 'string', // drive of the file to use (optional)
  metadata: false, // return metadata, not content
  $filter: 'string' // filter on the query. Needs to be URI encoded
};
```
