### ISSUE TITLE
Primero bug returning `state.data` in body of `upsertCase(...)` helper function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#30]
## Issue
The `data` object referenced in the helper function will return `state.data` even if other data has been assigned to this variable. 
```
upsertCase(
      {
        externalIds: ['record_id'],
        data,
      }
    )
```
This was causing errors [like this failure](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0634ed05-5b7a-754a-aa81-a387bfeb5839) where we were sending the WRONG data to Primero. See comments in this issue for more details: https://github.com/OpenFn/primero-thailand/issues/64

## Request
Fix this issue and deploy a new adaptor version. Then revisit Thailand [issue #64](https://github.com/OpenFn/primero-thailand/issues/64) tomorrow to implement the needed changes to make it work with this new adaptor version. 

To fix: https://github.com/OpenFn/language-primero/blame/main/src/Adaptor.js#L416

Please make this change on the mono repo.

**Comment by taylordowns2000** [comment]
@mtuchi , @aleksa-krolls , FYI, i've transferred this issue to the monorepo
