### ISSUE TITLE
Remove common.http

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#315]
The common.http operations, which use axios, are going to be replaced with helper functions based on `unidici`, see #314 .

This means that common.http is no longer needed and can be retired to beach on the Amalfi coast.

These functions, and their documentation, should be removed, and the common adaptor should have a major version bump.

Dependent adaptors should be updated. They may in turn have a major version bump if they happen to export http directly.

# Deprecation

Instead of just removing common.http, we could deprecate it for one major version.

We should mark it deprecated in the docs, and each time a http function is called, we should console.warn a deprecation notice.

I would prefer a clean break, and given the way we're set up, I think this makes more sense. Adaptors can continue to use old, compatible versions of common until they're ready to migrate, in which case there's no real need to use the deprecated API.

It's only if job authors want a softer migration that we should do this. Ie, if Mtuchi is often working across two major versions of common and getting confused about which APIs are available, we should be lenient for a while.

# Workarounds

I understand that many adaptors use `http.get/post` as general catch-all functions. This is useful if an adaptor supports N api calls from the backend, but the n+1th is not supported - you can just  call GET with the full URL in your job code.

Removing common.http will remove this escape hatch and make life harder for job implementers. The new cmmon.util helpers are not designed for job code, they are not like-for-like replacements.

I have a couple of answers to this!

1) If the adaptor wants to expose a general `get`, it _should_ provide its own `get` function which handles auth and stuff anyway. `msgtraph` at least does this. I.e., it should already be wrapping `http.get`, not exposing it directly. In which case the exported function can be updated. 

2) If the adaptor is directly exporting `http` or `http.get` to the job, and they really want to continue doing that, the adaptor could import the new `language-http` and export the relevant functions from there. There is nothing stopping them from doing that.

3) Maybe the code should run in a `language-http` job anyway, utilising the workflow better

4) If we really really really want to expose general http operations to jobs, then we can re-write common.http to wrap the new helpers in operations.

**Comment by josephjclark** [comment]
I would like to be aggressive here and just remove http, leaving is with a nice clean 2.0 adaptor.

Existing adaptors which have a version-locked dependency (ie, `"@openfn/langauge-common: 1.7.2"`) or a compatible version (ie, `"@openfn/langauge-common: ^1.7.2"`) will not be affected by the 2.0 release, and so the jobs attached to them are also unaffacted.

Adaptors - including legacy releases - with a of "any version" dependency may drift onto the 2.0 common, and so may break.

The fix would be simply to version lock the job back to common 1.8.

I think I'm comfortable with this - so let's go ahead and break things.

**Comment by josephjclark** [comment]
Removing common.http was too hard and too risky. It left the repo in a dangerously inconsistent state (although legacy adaptor would have been fine).

In #458 the old functions were deprecated.

Eventually we'll remove the common functions, but I'm not in a rush and suggest we migrate things as we touch them.

**Comment by mtuchi** [comment]
@josephjclark can we close this ?

**Comment by josephjclark** [comment]
I've closed the issue - http still exists but is deprecated.

We'll maybe delete the old stuff in a year or so.
