### ISSUE TITLE
Pin version of opinionator

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#330]
We use a dependency, `word-wrap`, which allows insecure regular expressions.

This is unlikely to be a concern for us. 

it affects `mailgun` and `salesforce`. It is likely to go away with mailgun when we update to the latest version of [mailgun.js](https://github.com/mailgun/mailgun.js#create).

Salesforce is a bit trickier because the problem comes out jsonpath, which is pretty unresponsive. But we can use pnpm to pin the version of `opinionator` to `0.9.3` - see https://github.com/estools/escodegen/issues/459. That should sort it now and forever.

This closes https://github.com/OpenFn/adaptors/security/dependabot/20

**Comment by mtuchi** [comment]
For salesforce `jsonpath` is only used in [lookup.test.js](https://github.com/OpenFn/adaptors/blob/main/packages/salesforce/test/metadata/lookup.test.js) so it should be a devDependency, Also the [JSONPath](https://github.com/OpenFn/adaptors/blob/main/packages/salesforce/package.json#L35C6-L35C14) package in sales force is not being used anywhere in salesforce adaptor. So we can remove it from dependencies
