### ISSUE TITLE
Add JSON schema verification to common

### ISSUE THREAD

**Issue by bensonmiller** [OpenFn/adaptors#340]
**Summary**
I have a use case where I'd like to verify JSON input payload against a predefined JSON schema. Given that schema verification is a common requirement in data processing pipelines, it feels like schema verification might be an appropriate addition in the `common` adaptor. Implementation feels like it is best handled by a dedicated library (i.e., Ajv), so this would imply additional dependencies are added to package.json.  I am not a professional JS developer, but I am open to providing a PR on this extension, conditional on interest from OpenFn core team.

**Implementation concepts**
The simplest "hello world" implementation might be to pass through the `ajv.compile()` and `ajv.validate()` functions directly to the adaptor, but I could envision a single function (perhaps `jsonSchemaValidate(schema,data)`) that would handle the schema compilation and validation in one stroke. This is probably sufficient for most use cases, although it's not very efficient to compile the schema before every validation.  For context, I'm new to OpenFn and I'm not aware if there are opportunities to cache objects, such as compiled schemas; absent such capability, the efficiency point might be irrelevant.

**Request**
I'd appreciate comments on whether the OpenFn maintainers view JSON schema validation as sufficiently attractive to warrant inclusion in the common adaptor, or whether a different (TBD) approach is recommended. Thank you in advance for your thoughts.

**Comment by bensonmiller** [comment]
I built a simple adaptor to prototype the concept described above. Approximately:

`
const Ajv = require('ajv');
const ajv = new Ajv();

/**
 * Validate JSON payload (from state.data) against JSON-schema schema.
 * @param {Object} schema - JSON-schema schema.
 * @returns {Object} - OpenFn state object with schema validation info
 */
export function validateJsonSchema(schema) {
  return state => {
     const validate = ajv.compile(schema);
     const schemaValid = validate(state.data);
   
     if (!schemaValid) {
       state.validationErrors = validate.errors;
     }
     state.schemaValid = schemaValid

     return state;
  }
}
`

**Comment by josephjclark** [comment]
Hi @bensonmiller , thanks so much for your comments, and for taking the time to draft a prototype!

I think this sounds like a great idea, I'll speak with the team and have a look at putting something together for you. Your code snippet looks great!

**Comment by bensonmiller** [comment]
Thank you @josephjclark! I’ll stay tuned.

**Comment by bensonmiller** [comment]
@josephjclark I've been thinking about this Issue. One thing that occurs to me is that I generally prefer to implement schema verification at the very edge of ingestion, so that I can return an error synchronously if the client fails to adhere to a contract. This doesn't mean that supporting schema verification in OpenFn jobs is without value (far from it), but it makes me wonder whether we might consider other approaches.

Specifically, I think about the OpenFn webhook ingestion endpoint. I  wonder whether we could configure schema verification on those endpoints. I hesitate somewhat to open this line of questioning because the logical conclusion is (probably) that configuring an OpenFn webhook would become as flexible as configuring an API gateway. That would be incredible for a variety of reasons, not the least of which is that it would allow OpenFn users (i.e., me) to avoid spinning up other cloud infrastructure to "front" the OpenFn ingestion endpoint.

The obvious alternative is to instantiate my own API gateway or some containerized proxy that enforces schema verification along with any other "edge" customizations that I want.

How do you and the OpenFn team think about this question?

**Comment by josephjclark** [comment]
@bensonmiller Thanks for the additional thoughts!

In Lightning we would handle this through the workflow. The first job invoked by  webhook trigger would use JSON schema to verify the payload received by the hook. If it's OK, it'll proceed with the job. If it fails, it'll report an error.

So basically you'd make the first job in a workflow a pure validation job, which doesn't really do anything other than check that the incoming state is OK.

Going forward, we will be adding support for richer conditions between jobs - including on triggers. So you'll be able to go to the link between the webhook and the first job, and add a condition which says "only trigger this job if the JSON schema is valid).

So we wouldn't want you to setup your own API gateway to handle this stuff - we'd want to handle the infrastructure for you using the workflow and richer, more nuanced relationships between triggers and jobs (and indeed relationships between jobs generally).

This all suggests to me that a schema validator would be useful.

I haven't forgotten any of this by the way. We're taking on some big projects at the moment so I'm afraid I don't have a lot of time. I have been exploring some of the security ramifications of using JSON Schema (and `ajv` in particular, which is a code generator). I think I'm satisfied but I'm still exploring!

**Comment by bensonmiller** [comment]
@josephjclark Thank you for this elaboration. I really like this direction.
