### ISSUE TITLE
new common-http: can't post JSON

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#377]
We've hit a problem in the new common http helpers.

Turns out we can't do `unidici.request({ method: 'POST', body: { hello: 'world' }})`

I though unidici would stringify the body for us, but it does not. We need to intervene.

I suggest we do the following:

* Add a `contentType` to the request options in the common helper. By default `contentType` is `json`. It can also be `form` or 'none',
* If the request has a `content-type` header, we IGNORE our content-type flag and do nothing automatically.
* Otherwise:
* * If contentType is `'json'`, and `body` has as truthy value, we set the content-type header to `application/json` and stringify the body
* * If contentType if `'form'`, and `body` has as truthy value, we set the content-type header to mulipart form (whatever that should be) and encode the form
* * If contentType is `none` (or falsy), we do nothing automatically

All this needs to happen in `common/util/http:request`. Where appropriate, wrapper functions should expose the `contentType` option.

Notes:
* Is `bodyType` better than `contentType`?
* Should it just be type?
* We now have a `contentType` for the request content, and `parseAs` for the response content. This doesn't feel so clean. What if we have `responseContent` and `requestContent` properties?
* If the request has a json content type header, and the body is not a string, we could try to stringify it.

**Comment by mtuchi** [comment]
Suggestion from @stuartc , the request should take whatever input it get and it's adaptor job to say what type of body should be passed to the `common:request`

**Comment by taylordowns2000** [comment]
noting that mtuchi needs to wait here until joe comes back. "this is low priority"

**Comment by josephjclark** [comment]
The thing is:
a) http has no more authority to automatically stringify json than the common helper
b) it's easy for an adaptor to override the default behaviour

I broadly agree that the function should be dumb and the adaptors should layer intelligence. But in this particular case I think auto-parsing JSON  at the helper level seems quite reasonable.

So I still think that if the request body is truthy, and no other information is provided, we should automatically stringify.

The helper functions will automatically handle the response data (if it's JSON anyway) - seems reasonable to the same for the request.

**Comment by mtuchi** [comment]
Added `requestBodyType` function which makes we have the correct body type and convert a plain json to string 
See 7463dbf
