### ISSUE TITLE
`mailchimp` bug where `md5` cannot be used in the new CLI

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/adaptors#383]
I don't appear to have access to `md5(...)` when running mailchimp `0.7.0` on cli `0.0.35`.

expression:
```js
startBatch({
  operations: state =>
    state.data.map(u => ({
      method: 'PUT',
      path: `/lists/<SOME-LIST-ID>/members/${md5(u.email)}`,
      body: JSON.stringify({
        email_address: u.email,
        status_if_new: 'subscribed',
        merge_fields: { FNAME: u.first_name, LNAME: u.last_name },
      }),
    })),
});
```

logs:
```

[CLI] ℹ Versions:
         ▸ node.js                       18.17.1
         ▸ cli                           0.0.35
         ▸ runtime                       0.0.21
         ▸ compiler                      0.0.29
         ▸ @openfn/language-mailchimp    0.7.0
[CLI] ✔ Loaded state from /tmp/state-1694184112-7-n3gbi.json
[CLI] ℹ Added import statement for @openfn/language-mailchimp
[CLI] ℹ Added export * statement for @openfn/language-mailchimp
[CLI] ✔ Compiled job from /tmp/expression-1694184112-7-ycpep2.js
[R/T] ℹ Resolved adaptor @openfn/language-mailchimp to version 0.7.0
[R/T] ✘ Error in runtime execution!
[R/T] ✘ ReferenceError: md5 is not defined
[CLI] ✘ Error: runtime exception
[CLI] ✘ Took 580ms.
```

https://github.com/OpenFn/adaptors/blob/f4439b104f8a6f9a32386059b8d2562c8efa944a/packages/mailchimp/src/Adaptor.js#L431

**Comment by mtuchi** [comment]
@taylordowns2000 why do you need `md5`? have you tried to run the operation without `md5`?

**Comment by taylordowns2000** [comment]
Good q! We're using it for two reasons:
1. It's what Mailchimp recommends you use when hitting that API. (Presumably so you don't have user emails in the clear in your HTTP requests. See image for mailchimp doccumentation)
2. It's what that job has been running with successfully for several years.

<img width="1032" alt="image" src="https://github.com/OpenFn/adaptors/assets/8732845/1f123e75-f6b8-4ce2-a998-5359f4cd4bb9">

I'm actually much **more interested in reason number 2** (cc @josephjclark). Are there classes of things that the new CLI doesn't support? (Like exporting the whole `axios` module? Or using `beta.each`? Or, in this case, using that `md5` export?)
