### ISSUE TITLE
Unit Testing New HTTP

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#386]
We currently have two issues in the new HTTP adaptor which are hard to unit test:

1) redirects
2) form data

This issue is to a) validate whether form and redirect are working, and b) work out how to unit test them.

## Demo Server

Here is a simple koa server which listens for redirect and form upload requests
```
import Koa from "koa";
import multer from "koa-multer";

const app = new Koa();

app.use(multer().single());

app.use(async (ctx) => {
  console.log(">>", ctx.url);
  if (ctx.url === "/form") {
    console.log(" * FORM");
    console.log(ctx.req.body);
    ctx.response.status = 200;
  } else if (ctx.url === "/redirect") {
    console.log("redirecting!");
    ctx.response.status = 301;
    ctx.response.set({ Location: "http://localhost:2222/foo" });
  } else {
    ctx.response.status = 200;
    ctx.response.body = "ok";
  }
});

app.listen(2222);
```

To run, install `koa` and `koa-multer` and do `node server.js`

## Redirects

Using the new HTTP adaptor right now, the redirects work as expected.

Annoyingly, the `undici` interceptor mock doesn't seem to work. I am not sure why this should be. If we re-target the unit tests at this server, they seem to work.

We should investigate this a bit further and try to understand why the interceptor doesn't work.  Maybe there's an issue on the `undici` github. If it continues to misbehave, we can re-write the unit test to use a real server, similar to the one above.

## Form Data

Using the `main` http adaptor, the following job will upload form data:
```
execute(
  post("http://localhost:2222/form", {
    form: {
      id: "fake_id",
      parent: "fake_parent",
      mobile_phone: "fake_phone",
    },
  })
);
```
In the console, this outputs a JSON-like object with the form data inside:
```
[Object: null prototype] {
  id: 'fake_id',
  parent: 'fake_parent',
  mobile_phone: 'fake_phone'
}
```

If I use the new adaptor from the monorepo, the same job outputs undefined.

This tells me that our new formdata stuff isn't working.

It is ESSENTIAL that the new adaptor passes a manual test like this. Ideally we should also have an automated test. I don't think we can use interceptors here, it's a bit too hard to extract the form body. But we could create a koa server and have it return a JSON representation of the form - I think under the circumstances that would be acceptable

**Comment by mtuchi** [comment]
@josephjclark 
The mock system is not aware of form-data, There was an [issue on undici](https://github.com/nodejs/undici/issues/1322) which sort of address callback body option to return any input type. But it doesn't seem like it's working

**Comment by josephjclark** [comment]
For the form data I've updated the test to verify that our request function is parsing the `form` data into an actual FormData instance and sending that up to the server. That's good enough for me. The server test is working.

For the redirect we're limited by the capabilities of the mock. I've spun out https://github.com/OpenFn/adaptors/issues/402 to track but for now we'll just remove the test
