### ISSUE TITLE
New HTTP Logging

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#388]
The existing HTTP adaptor will log this on a successful request (via the CLI)
```
POST request succeeded with 200 ✓
```
If the request responds with a 404, we seem to get this:
```
[R/T] ✘ Failed job job-1 after 325ms
[R/T] ✘ ERR_BAD_REQUEST: Request failed with status code 404
```
I think we can offer better feedback than this.

We should use a pattern similar to what server-side loggers do, like this:

```
GET www.example.com/patient?id=bob - 200 in 163ms
POST www.example.com/patient - 404 in 2192ms
```
Note that the log should _always_ come after the response and before we throw any errors.

We may want to tweak the format but we should keep it simple.

We can consider including a config option to disable URL logging, in cases where URLs may contain sensitive information (although to be fair, it's bad practice to put sensitive stuff in a publilcly visible URL).

Note: There is a wider story here about how adaptor logs look in the CLI, because they appear without a namespace like [CLI] or [R/T].  I've created #387 to cover this, but that should not be included in this work.

**Comment by josephjclark** [comment]
Maybe we can include the status message? like:
```
POST www.example.com/patient - 404 NOT_FOUND in 2192ms
```

**Comment by mtuchi** [comment]
@josephjclark how do we calculate the responseTime in `ms` ?
For example `2192ms` in `POST www.example.com/patient - 404 NOT_FOUND in 2192ms`

**Comment by josephjclark** [comment]
@mtuchi Use `Date.now()` - I'll DM you

**Comment by mtuchi** [comment]
Added HTTP logging on #373 cc @josephjclark
