### ISSUE TITLE
`salesforce` new `bulkQuery()` function failing for aggregate queries

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#395]
## Issue 
A user is trying to run a Salesforce SOQL query like this where there is an aggregate query (note the nested `(SELECT...)` query within the bigger query). 
```
SELECT Name, Email, (SELECT Campaign_Tag_Name__c FROM CampaignMembers
  WHERE Campaign.RecordType.Name = 'Grupos, RTs ou Áreas Temáticas' and  Campaign.IsActive = true)
FROM Contact
WHERE Id in (SELECT Contact__c FROM Deleted_Campaign_Member__c WHERE CreatedDate > ${state.lastSyncTime}
```
This query should work, but when using the `bulkQuery()` adaptor function, they're encountering the following error message: 
_Aggregate Relationships not supported in Bulk V2 Query **with CSV content type.**_

They're testing with Salesforce API `v59.0` which SHOULD support aggregate queries. [See SF documentation](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_using_bulk_query.htm) for what is _not_ supported (which shouldn't impact us). 

Per this error message, it sounds like we're not properly specifying `'Content-Type': 'application/json` somewhere in the adaptor... it is possible that in our request to Salesforce (or in a later request when we check on the job results), we're mistakenly setting the content type to `text/csv`?

See the project's [related Github issue](https://github.com/OpenFn/gife/issues/12).

**Comment by mtuchi** [comment]
It doesn't seem to be the issue with the adaptor function, rather it's limitation with [Bulk API 2.0](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/query_create_job.htm) It has a limitation on **Parent-to-child [relationship queries](https://developer.salesforce.com/docs/atlas.en-us.246.0.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_understanding.htm). (Child-to-parent relationship queries are supported.)**

**Comment by mtuchi** [comment]
@aleksa-krolls can we close this issue since it's not an issue with the `bulkQuery` function
