### ISSUE TITLE
Commcare: don't use language-http

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#414]
commcare currently depends on language http. It also uses common.http, which is a bit mad

We should refactor so that it uses the new http helpers in common

**Comment by mtuchi** [comment]
We will need a commcare sandbox for testing all functions since we don't have unit test for this adaptor

**Comment by josephjclark** [comment]
Even worse, commcare also users superagent.

I'm really keen to tidy this up, but yes we will need a sandbox

**Comment by aleksa-krolls** [comment]
hey @josephjclark we finally got a CommCare sandbox (LP credential `CommCare Demo Project`). 
Is this something Hunter can take on? Or Mtuchi?

**Comment by josephjclark** [comment]
Awesome - it's a nice task for Hunter!

**Comment by hunterachieng** [comment]
@josephjclark  Do I do the same thing as I did with openmrs?

**Comment by josephjclark** [comment]
@hunterachieng yep - it's basically exactly the same thing :)

Now that we've got a sandbox we'll have to get some kind of test job setup to ensure we don't break anything.

**Comment by aleksa-krolls** [comment]
hey @hunterachieng how's it going here? Any questions or blockers? cc @AishaHassen

**Comment by hunterachieng** [comment]
@aleksa-krolls Its going well. will be done by today

**Comment by hunterachieng** [comment]
@aleksa-krolls  Its currently under the second round of reviews. If approved, I will combine it with the next commcare issue

**Comment by hunterachieng** [comment]
@aleksa-krolls  The review is done and the code has been merged to this [`branch`](https://github.com/OpenFn/adaptors/tree/release/commcare). We are going to combine all the commcare related tasks here and then release all of them together

**Comment by aleksa-krolls** [comment]
Noted thanks @hunterachieng. Once released please let me and @AishaHassen know so we can check out the docs and functions and provide feedback... ty!
