### ISSUE TITLE
http @5.x: response data is huge

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#432]
http 5.x. which uses axios,  writes the a response object to result state. It

This includes 20k of minified JSON.

A lot of the damage seems to be from the `agent` key.

I think this has been happening forever and it's because we just "blindly" write the axios response straight to state.

Discuss.

**Comment by josephjclark** [comment]
CLI 0.1 (5 months old) also exhibits the same behaviour

**Comment by mtuchi** [comment]
After a close investigation with multiple version of http adaptor here is the summary 

```
get("https://jsonplaceholder.typicode.com/todos/1")
```

| platform | version  |
| -------- | -------- |
| core     | v1.5.1   |
| node     | v18.17.1 |
| cli      | v0.4.6   |

| http   | output size | state.response keys                                                                       | state.data keys                          |
| ------ | ----------- | ----------------------------------------------------------------------------------------- | ---------------------------------------- |
| v3.0.0 | 4.0K        | no _state.response_                                                                       | [ 'body', '__cookie', '__headers' ]      |
| v4.0.0 | 124K        | [ 'status', 'statusText','headers', 'config', 'request', 'data', 'httpStatus', 'message'] | [ 'userId', 'id', 'title', 'completed' ] |
| v5.0.0 | 112k        | [ 'status', 'statusText','headers', 'config', 'request', 'data', 'httpStatus', 'message'] | [ 'userId', 'id', 'title', 'completed' ] |

**Comment by mtuchi** [comment]
In `state.response.request` we have a-lot of data that is not useful in most cases, 
<details><summary>Here is the list of the state.response.request</summary>
<p>

```
[
  '_events',
  '_eventsCount',
  '_maxListeners',
  'outputData',
  'outputSize',
  'writable',
  'destroyed',
  '_last',
  'chunkedEncoding',
  'shouldKeepAlive',
  'maxRequestsOnConnectionReached',
  '_defaultKeepAlive',
  'useChunkedEncodingByDefault',
  'sendDate',
  '_removedConnection',
  '_removedContLen',
  '_removedTE',
  'strictContentLength',
  '_contentLength',
  '_hasBody',
  '_trailer',
  'finished',
  '_headerSent',
  '_closed',
  'socket',
  '_header',
  '_keepAliveTimeout',
  '_onPendingData',
  'agent',
  'socketPath',
  'method',
  'maxHeaderSize',
  'insecureHTTPParser',
  'joinDuplicateHeaders',
  'path',
  '_ended',
  'res',
  'aborted',
  'timeoutCb',
  'upgradeOrConnect',
  'parser',
  'maxHeadersCount',
  'reusedSocket',
  'host',
  'protocol',
  '_redirectable'
]
```
</p>
</details> 

My proposal for `state.response.request` is to keep only the following keys 
```
{ method, path, host, protocol }
```
cc @josephjclark

**Comment by josephjclark** [comment]
@mtuchi are the outputs the same on core and CLI, or do they change across versions?

This implies that the whole response object was added somewhere after 3.0 of the http adaptor.

Most of the data seems to be in `response.agent`, `response.res` and `response._redirectable` (this seems to be the worst)

I agree with your proposal - the only other thing I'm tempted by is `_headers`, so that one can interrogate the request headers (which seems useful). Is there any other way to get the request headers?

The other strategy to approach this would be to remove any properties starting with `_` from the whole response object. Perhaps in a cleanup step at the end of a job - that way you have the whole response to play around with inside the job, but the only thing that gets serialized is the non-private keys.

What I like about that approach is that there's a simple rule:  response serialisation ignores `_` properties.

Come to think of it, maybe that's a rule which the runtime should adopt - then we can fix this at a very low level for all jobs and adaptors. Works great until someone wants to serialize an `_id` key in their data :thinking: Ok, so maybe that's a step too far...

**Comment by josephjclark** [comment]
Ok, @mtuchi , can we please:

1) Add a function to common called `removeUnderscoredProps`, which recursively removes all properties starting with `_`. It should return a new obejct, rather than mutating the otihinasl You can probably find an npm or lodash library to help if you don't want to write that yourself.

2) At the end of http execute, call `removeUndescoredProps` on `state.response`

This would technically be a major bump but I really don't think anyone will care. Plus it'll be a short-lived release with 6.0 on the horizon. I suggest we call it a minor

**Comment by josephjclark** [comment]
@mtuchi let's do the easy thing for now. I'll merge your PR and we can release tomorrow
