### ISSUE TITLE
Test version `bump @azure/ms-rest-nodeauth and tedious`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#44]
### Description
Write a test to test a version bump `@azure/ms-rest-nodeauth and tedious` `v8.0.1` to [v15.1.0](https://github.com/tediousjs/tedious/tree/v15.1.0)

**Comment by taylordowns2000** [comment]
This is closed in @mtuchi 's mssql migration; and the issue of DB testing is here: #43
