### ISSUE TITLE
`http` Scrub final http response

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#453]
### Short Description 
Scrub the http response to remove sensitive data like password and API keys

### Implementation Notes 
See if you can use this npm packaage [@zapier/secret-scrubber](https://www.npmjs.com/package/@zapier/secret-scrubber) to scrub the final `state.response`, `state.results` At the end of the job execution.

<details><summary>Expand to see implementation example using @zapier/secret-scrubber</summary>
<p>

```
import { scrub, findSensitiveValues } from '@zapier/secret-scrubber';
const jsonResponse = {
  user: 'admin',
  password: 'secretpassword',
  nested: {
    api_key: 'sensitiveapikey',
    other: 'data',
  },
};

const results = scrub(jsonResponse, findSensitiveValues(jsonResponse));

console.log(results);
// The result of console.log
{
  user: 'admin',
  password: ':censored:14:b1b3305309:',
  nested: { api_key: ':censored:15:1164c93850:', other: 'data' }
}
```
</p>
</details> 

<details><summary>Expand to see Suggested code change in `http` adaptor</summary>
<p>

```
export function execute(...operations) {
  const initialState = {
    references: [],
    data: null,
  };

  return (state) => {
    return commonExecute(
      ...operations,
      scrubResponse
    )({ ...initialState, ...state });
  };
}

function scrubResponse(state) {
  if (state.response) {
    scrub(state.response, findSenstiveValues(state.response));
  }
}
```
</p>
</details> 

### Tasks
- [ ] Use `scrub` and `findSensitiveValues` helper function in `http` adaptor to remove sensitive data

### Questions?
- Should this be a util function in `common` ?
- Do we ever want to scrub `state.data` or the entire `final state`?
- What if the first job in my workflow fetches a token then the second job in my workflow uses that token to query data, If we scrubbed the final state of job one that means job two will fail. Do we ever want job code to do this process of Authentication or this should always be the adaptor job ?
- What else should we scrub in the final state ?
> In some cases if you have chain of get() operation, `state.data` gets pushed to `state.references`. Do we need to `scrub` state.references?

**Comment by taylordowns2000** [comment]
Hey @mtuchi and @josephjclark , it's unclear whether this is an issue in the new `http` adaptor or not. While we do need to do _something_ about this (read the [**_whole_** thread](https://openfn.slack.com/archives/C0394D0GBUN/p1703149940085049) please) it might be best done as a patch to the current http adaptor or as an addition to the new http adaptor.

**Comment by mtuchi** [comment]
Hiya @taylordowns2000 @josephjclark , I have two questions for you 
- Should we patch on current HTTP vs new Epic
> If we don’t do on existing HTTP adaptor, would we deprecate it and move existing jobs over to new code (there only 12 jobs)?
- Should we scrub final_state at a worker, adaptor or UI level
>If it happens at adaptor level, What if some job requires details (API token) from the final_state ?

**Comment by mtuchi** [comment]
Ref: https://github.com/OpenFn/kit/issues/554

**Comment by josephjclark** [comment]
This has been resolved for now by the runtime.
