### ISSUE TITLE
Review final state for all adaptors

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/adaptors#454]
Building off the back of #453 , we need a systematic review of all adaptors (priority order) if we're going to be sending a copy of final_state back to lightning.

**Comment by mtuchi** [comment]
@taylordowns2000 18 of our adaptors have this pattern for the final state 
```
const nextState = {
    ...composeNextState(state, response.data),
    response,
  };

// or 
const nextState = composeNextState(state, response);
```
This means we expect `state.response` that **might** contain sensitive data. Here is the list of the adaptors with that pattern.
  
- [ ] asana `Rest API`
- [ ] azure-storage
- [ ] facebook `Rest API`
- [ ] fhir `Rest API`
- [ ] godata `Rest API`
- [ ] googlehealthcare `Rest API`
- [ ] kobotoolbox `Rest API`
- [ ] mailchimp `Rest API`
- [ ] mailgun 
- [ ] medicmobile `Rest API`
- [ ] msgraph `Rest API`
- [ ] nexmo 
- [ ] ocl `Rest API`
- [ ] postgresql 
- [ ] progres
- [ ] rapidpro
- [ ] sftp
- [ ] template `Rest API`

Also there are 3 adaptors that use this pattern
```
const nextState = {
    ...composeNextState(state, result),
    result,
  };

// or 
const nextState = composeNextState(state, result);
```
- [ ] hive
- [ ] mongodb
- [ ] salesforce

**Comment by mtuchi** [comment]
In the case of `http` adaptor https://github.com/OpenFn/adaptors/blob/main/packages/http/src/Adaptor.js#L110-L112
```
return {
    ...composeNextState(state, respWithCookies.data),
    response: respWithCookies,
};
```

**Comment by mtuchi** [comment]
No action required from the adaptors level. Runtime and worker will remove final `state.response` [See the ticket here](https://github.com/OpenFn/kit/issues/554). Also @taylordowns2000 will create a ticket on lighting for scrubbing the output panel
