### ISSUE TITLE
Salesforce: add function(s) to make a request to a REST API 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/adaptors#464]
Add functionality to the SF adaptor to make a request to a REST API. Add this to the Salesforce adaptor once you get it working via HTTP. 

Test this using the WaterAid credential in LP named: "Water Aid - API Only Sandbox". If you POST to the following endpoint the system will create a Contact: `wateraiduk--config2.sandbox.my.salesforce.com/v33.0/actions/custom/flow/POC_OpenFN_Test_Flow`

After sending the request confirm with Tom via Slack that the correct resource was created. 

See Slack [thread](https://openfn.slack.com/archives/C068N0ZC2DV/p1705489875769089) with the original request. See helpful Docs below:
1. https://help.salesforce.com/s/articleView?id=sf.flow_distribute_system_rest.htm&type=5
2. https://astreait.com/Calling-REST-API-from-Flows-in-Salesforce/
3. https://www.asagarwal.com/step-by-step-guide-to-calling-flow-from-an-api/
4. https://www.postman.com/salesforce-developers/workspace/salesforce-developers/request/12721794-684df392-aebc-4ff8-9ff7-30f6e4e88b74
5. https://www.salesforceben.com/introduction-salesforce-flow/#:~:text=What%20are%20Salesforce%20Flows%3F,help%20of%20a%20Salesforce%20developer

**Comment by daissatou2** [comment]
Moving to `icebox`. 

Message from Tom: "Let's leave this parked for now. We are currently not able to call the 3rd Party functionality within Salesforce Flow until we get clarification from that side, if we get a reply at all so don't want to currently devote any further time to these efforts."

**Comment by mtuchi** [comment]
This was done and released on https://github.com/OpenFn/adaptors/pull/465
