### ISSUE TITLE
Salesforce `SOQL` limits docs

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#481]
### Description
They query functions has couple of limits but to name a few important limits 
- 2,000 results per request (API version 28.0 and later),
- 4,000 characters for each string within a WHERE clause.

### Request
Update the documentation for `query()` function to include the limits highlighted above, Learn more about [SOQL Limits here](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_soslsoql.htm)

**Comment by aleksa-krolls** [comment]
@mtuchi we can close this now, yes? Please do, if yes

**Comment by mtuchi** [comment]
@aleksa-krolls i working on joe's feedback on this pr #501

**Comment by christad92** [comment]
@mtuchi can this be closed now?

**Comment by mtuchi** [comment]
@christad92 yes closing this as it was addressed in #506
