### ISSUE TITLE
common: expandReferences should interpret json path strings

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#483]
## Overview

Allow JSONPath strings to be passed into operations seamlessly
```
post('www', '$data.patients')
```

## Background

We have a really big problem in job code right now where it's hard to get a value of state (a basic verb of our system).

I could do any of these things (and they all exist in job code today):
```
post('www', data.patients) // often the cause of errors!
post('www', dataValue('patients'))
post('www', (s) => s.data.patients)
post('www', JSONPath('$data.patients') // I forget the function name but it's something like this
```

Most modern adaptors use `expandReferences` on an operation's arguments,  allowing the function to be passed. This is probably my favourite pattern.

`dataValue()` probably ought to be deprecated (#484)

The JsonPath one is nice, but also a little awkward and you have to reach for a non-operation function (and hope it was exported by the adaptor).

## Solution

This issue proposes to add JSONPath support to expandReferences, so that you can do this:

```
post('www', '$data.patients')
```

Any string value starting with `$` would be treated as a JSON path chain and we'd try to read the path.

Obviously for literal strings genuinely starting with `$` this is a bit of a problem - but I imagine these are super rare at this operation level. The workaround would be to pass a function, ie `post('www', () => '$1,000')`.

A flag on `expandReferenences` could suppress this behaviour for operations where it is more likely to be a problem, ie:
```
const [resolvedAmount] = expandReferences(state, amount, { jsonPath: false })
```

**Comment by josephjclark** [comment]
@mtuchi @taylordowns2000 @stuartc I'd love to get your thoughts on this. I think it's a really easy win!

**Comment by mtuchi** [comment]
@josephjclark my only feedback is the function should use `$.data` and not `$data`. Also i am not sure how this will affect `parseXML` since it uses the `$` [See parseXML L172-L190](https://github.com/OpenFn/adaptors/blob/main/packages/http/src/Adaptor.js#L172-L190)

**Comment by josephjclark** [comment]
Thank you @mtuchi ! parseXML is a great use-case, I'll take a look.

Do you think it'll be useful in your job writing? Do you think you would you use it over `(state) => state.data`?

I also need to think about docs. How do we make it clear that json path strings are supported? Adaptors will need patching to support this.

**Comment by josephjclark** [comment]
After a quick chat with taylor a better, and free-er solution, might be to use the compiler to compile `$.a.b.c` into `(state) => state.a.b.c`

This would work natively with all adaptors (well, all adaptors that expand references), it doesn't require extra documentation, and its easy to understand.

It's basically JSON path, against state, as a first class language statement

**Comment by mtuchi** [comment]
@josephjclark i will definitely use this pattern `$.a.b.c` than `state => state.a.b.c`. Let me know if you have looked into `parseXML` i am curios to see how it will work

**Comment by josephjclark** [comment]
@mtuchi parseXML will be completely unaffected
