### ISSUE TITLE
common: add a catch() operation

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#496]
Catch is probably a reserved word so we'd need to think about that

But the idea is that if you put an operation in a catch, it'll call a callback on error. So you can do:
```
catch(upsert, (state, error) => {
   console.error(error)
})
```
This lets you intercept errors and could be useful for  debugging.

If you still want the job to fail, you need to re-throw the error object.

**Comment by mtuchi** [comment]
@aleksa-krolls  I need more information about the implementation before adding estimation. I will have a sync with joe and get back to this issue

**Comment by mtuchi** [comment]
On hold until i sync with @josephjclark

**Comment by josephjclark** [comment]
After consultation with @stuartc I think a better approach to this is to make this work on all operations:
```
get($.data.url).catch(() => {
	// throw to abort, or else we'll continue
})
```

We should be able to add runtime support for this. I don't think it's too difficult.

This would enable all operations to be catchable, on all adaptor versions, without introducing new functions to common

**Comment by mtuchi** [comment]
@josephjclark does this mean we should support for `.then()` also ?

```
get($.data.url).then(() => {
	// do something  with the data 
})
```

**Comment by josephjclark** [comment]
@mtuchi huh - that would be a neat way to handle callbacks and save us from the awkward extra argument. I think I like it!

**Comment by aleksa-krolls** [comment]
@mtuchi can we move this back to Client Backlog?

**Comment by josephjclark** [comment]
Yes please @aleksa-krolls - I think this is actually my issue now!

**Comment by josephjclark** [comment]
Runtime now supports `.catch()` on any operation :exclamation: :exclamation: :exclamation:
