### ISSUE TITLE
Database configuration schemas

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#511]
### Description
 
 Most of database adaptors are using `type: uri` for `hostUrl` which forces the input to contain a protocol. This is not accurate in most cases because a database `hostUrl` can be `hostname`, `ipaddress` or `uri` 
 
 ### Request in few words
Update the `hostUrl` to use the following schema 
```
 "host": {
      "oneOf": [
        {
          "type": "string",
          "format": "hostname"
        },
        {
          "type": "string",
          "format": "ipv4"
        },
        {
          "type": "string",
          "format": "uri"
        }
      ]
    },
 ```
 
 #### Database Adaptor List
- [x] mssql
- [x] mysql
- [x] postgresql
- [ ] ~mongodb~

**Comment by mtuchi** [comment]
@josephjclark should database URL be formatted as `URI` ? Eg `mongodb://xxx`

**Comment by josephjclark** [comment]
The strictness of this probably depends on the adaptor, the client, and the underlying implementation. I don't think I can give you one answer for all databases.

What I would say is: if schema validation is too string and its getting in the way, just make it a string type . The `hostUrl` as you've shown it in the PR description looks way too complicated and for no real benefit.

**Comment by aleksa-krolls** [comment]
@mtuchi @josephjclark should we prioritize this in Mtuchi's backlog?

**Comment by josephjclark** [comment]
@aleksa-krolls it's probably something to fix reactively, as it becomes a problem. I'm not sure it's a priority.

**Comment by mtuchi** [comment]
I have changed the format from `hostname` or `uri`  to `string` for 
- [x] postgresql
- [x] mysql
- [x] mongodb
- [x] mailgun
- [x] hive

See #516
