### ISSUE TITLE
`salesforce` Refactor the OAuth 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#527]
### Description 

We should refactor salesforce oauth one final, glorious time.

We should not mess with oath keys and we should leave them as snake_case. To make this less untidy, we should nest all oath keys inside an oath object.

That means we'll have config objects / credentials which look like this:
```
{
   "apiVersion": "42",
   "loginUrl": "www.",
   "oauth": {
       "access_token": "blah"
    }
}
```

This way, all lightning needs to do is append the oath payload to the oath key. Simples.

All other oauth adaptors will follow the same pattern.

## schema design

We need to think about schema design too, but maybe this is a separate issue.

Right now, the oauth schema does not include important properties  like "loginUrl" or "apiVersion". Those are in the main schema.

We need to ensure that both schemas are accurate. Or maybe  merge them - JSON schema supports conditional dependencies, so we can have rules like "security token is required IF oath is not set".

This depends on Lightning though, because Lightning team need to build the form properly.

`state.configuration.oauth`

**Comment by christad92** [comment]
The implementation we are resorting to is one that will allow admins define their context-specific variables when setting up clients. These variables will be returned when a credential called within a job. see #2034

**Comment by mtuchi** [comment]
Closing this issue since it will be addressed on lightning side, See https://github.com/OpenFn/lightning/issues/2035
