### ISSUE TITLE
`satusehat`: new adaptor to handle auth and expose http functions

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#529]
## Background
[SATUSEHAT](https://satusehat.kemkes.go.id/platform/docs/id/playbook/) is the Indonesian government's FHIR health information system. A customer wants to send FHIR-format data from CommCare to SATUSEHAT, so we need to create a new adaptor to support [this project](https://github.com/OpenFn/asri).

## Request
Create a new `satusehat` adaptor that: 
1. handles authentication
2. exposes all `http` functions so that we can send requests to the dozens of API endpoints the adaptor exposes (incl. `/patient`, `/encounter`, etc.)

## To test
- Use this postman collection: https://www.postman.com/satusehat/workspace/satusehat-public/request/30206597-5a1e7e8e-8381-4854-953f-761a622cca86
- For the *staging* API credentials, see LP `HIH ASRI SATUSEHAT creds` for the `organization id`, `client key`, etc. 
- Once auth is built in the adaptor, you can trying using the adaptor to send a GET request to [this Organization endpoint](https://www.postman.com/satusehat/workspace/satusehat-public/request/30206597-5d218374-181b-465d-a2df-3ce557f165a8) (and use the `organization id` from the LP credential as the parameter `/api/Organization/:id`)

Staging login url: `https://api-satusehat-stg.dto.kemkes.go.id/oauth2/v1/accesstoken?grant_type=client_credentials`

**Comment by hunterachieng** [comment]
@aleksa-krolls  I have talked to @josephjclark  and we are good to start on this task
