### ISSUE TITLE
`salesforce` rename `create` to `insert`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#552]
### Description

Salesforce `create()` function should be renamed as `insert()` because that is what the DB operation is called in salesforce. 

Is there a way to make this change but also ensure backwards compatibility with jobs that use `create()`?

### Context 
When we use the word “create” the user thinks we’re creating metadata, instead of “inserting” data into an existing `table/object`

**Comment by mtuchi** [comment]
According to [jsforce](https://jsforce.github.io/document/#create), create is synonym of `insert`.  The recommended approach is we add an alias for `insert` which is similar to `create`.

<img width="763" alt="Screenshot 2024-05-30 at 5 01 44 PM" src="https://github.com/OpenFn/adaptors/assets/6592749/c581f813-6034-41cd-88bf-b090565eeb40">

Another recommendation is we improve the documentation to clearly state `create()` function. Only creates new sObject record. Does not create sObject metadata

**Comment by josephjclark** [comment]
Sorry @mtuchi I was supposed to leave a comment on this - got distracted

That's a useful bit of documentation. If `create` and `insert`  are synonyms then I'm quite happy to alias it in the adaptor. Doing anything more dramatic that needs some serious consideration.

**Comment by josephjclark** [comment]
Done in #632
