### ISSUE TITLE
dhis2 metadata helper not loading correct TEI Attribute Ids

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#557]
## Describe the bug and expected behavior 
On this [Non-FHIR to FHIR workflow](https://app.openfn.org/projects/fdfdf286-aa8e-4c9e-a1d2-89c1e6928a2a/w/b0849f2a-ac91-4689-b813-ff80c077a2cc?s=d3ef54de-4b6c-4655-a8aa-21d504f1dc27) I updated the credential in the DHIS2 step because Tracker is broken on the older play instance. 

I noticed that then, the Metadata helper did not refresh. It's still showing me the ids from the prior DHIS2 instance, not the newly connected ones. I know this, because if I use the ids from the Metadata Helper, then the DHIS2 step fails with `409 error: Invalid attribute`. I then logged into DHIS2 and found this list of attributes which are _not_ displayed in the Metadata Helper. 

What's strange is that even when I create an entirely _new_ workflow ([see here](https://app.openfn.org/projects/57862287-23e6-4650-8d79-e1dd88b24b1c/w/7ce701c0-3eed-4c2d-9d70-02aeab306a03?s=c162a68b-0df4-46a2-a1aa-d0b6eee0ab35)), the Metadata Helper still seems to pull Ids from another DHIS2 instance, and not the `v40.3.0` (which is the credential I'm using). 

### TEI Attributes in DHIS2 v40.3.0:
![tei_attributes_40](https://github.com/OpenFn/adaptors/assets/16758106/c0f3857f-88d2-4524-a695-14e19f4a21b7)

### Wrong TEI Attribute Ids (none of these are in the above screenshot)
Not sure where the adaptor is getting these values --> but they do not exist in my dhis2 instance. 
<img width="634" alt="Screenshot 2024-05-14 at 11 04 17 AM" src="https://github.com/OpenFn/adaptors/assets/16758106/af2be5f5-d13a-48eb-a634-1db30af13c6c">

## To Reproduce
1. Create a new workflow
2. Select Adaptor: `dhis2 v4.0.4`
3. Paste in the below job code --> try picking the mapping for one `attribute` using the Metadata Helper
4. Run the job --> see `Conflict 409 error: Invalid attribute`
5. Then try the second job code (which has ids I manually found) --> see successful import

### expression.js
See [this workflow]() or the below code. 
Adaptor: `dhis2 v4.0.4`
```
// TRY FIRST! THIS JOB USES IDS FROM METADATA HELPER - FAILS! ====//
create("trackedEntityInstances", {
   orgUnit: "Rp268JB6Ne4" /*Adonkia CHP*/, 
   trackedEntityType:"nEenWmSyUEp" /*Person*/, 
   attributes: [
     {
      attribute: "dLHLR5O4YFI" /*PEPFAR ID*/, 
      value: "234"
    }
   ]
}
 );

//THIS JOB USES IDS MANUALLY FOUND IN DHIS2 INSTANCE - WORKS! ==//
create("trackedEntityInstances", {
  orgUnit:  "Rp268JB6Ne4" /*Adonkia CHP*/,
  trackedEntityType: "nEenWmSyUEp" /*Person*/,
  attributes:  [
    {
      attribute: "w75KJ2mc4zz" /*First Name*/,
      value: "Taylor"
    }
  ]
});
```

### state.json
Latest version of the dhis2 play instance: https://play.dhis2.org/40.3.0/

```json
{
  "hostUrl": "https://play.dhis2.org/40.3.0",
  "username": "admin",
  "password": "district"
}
```

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @josephjclark @christad92 discovered that the DHIS2 Metadata helper is not working in the app right now. See above.

**Comment by josephjclark** [comment]
Two possibilities here...

1) Lightning is sending the wrong credential to the CLI
2) The CLI is returning cached metadata

Remember that right now, metadata is generated by Lightning calling out to the CLI's `metadata` command and returning the result.

The CLI caches results. The cache uses a key from the serialized credential object plus the adaptor version. If the credential hasn't changed, but the backend data has, the CLI will return you stale data from the cache (I'm sure there's an issue about this somewhere, a manual refresh button, but it's basically an unsolved problem).

In this case, if you're changing the credential  (including the host url), the CLI should be working fine. So I suspect the problem is with lightning?

**Comment by josephjclark** [comment]
The metadata panel in ligtning has a little thing at the bottom which shows the date the metadata was generated

**Comment by aleksa-krolls** [comment]
Yeah the date looks all right - but the Ids are still wrong. So I wonder if there is some caching issue. 
Then @christad92 can you pls move this issue over to Lightning then?

**Comment by josephjclark** [comment]
Wait the date looks correct? Like it's a recent date?

**Comment by josephjclark** [comment]
I've just setup on demo.openfn.org and I see the same list you do in your lightning screenshot. This is not the same list as in your dhis2 screenshot. This is suspicious :thinking:

**Comment by josephjclark** [comment]
I can confirm that the adaptor is using the `hostUrl` provided in the credential object. So if the correct  credential goes to the CLI, and the CLI does not use the cache, it should be doing the right thing.

**Comment by aleksa-krolls** [comment]
@josephjclark just ran another test. Metadata Helper `datetime` is _not_ updating when I create a new Workflow... so maybe it is a caching issue on lightning. 
https://www.loom.com/share/4cc26a2db88446de95a014d0a88109b7?sid=b4b8ec7f-2f94-4c78-b4e0-710199f69d04

**Comment by josephjclark** [comment]
Alright I've worked it out!

What's happening is that the adaptor is fetching the list of `attributes` for that instance. But what we actually want is the list of `trackedEntityAttributes`.

It's an error in the metadata function for the adaptor. I will raise a fix now.
