### ISSUE TITLE
commcare: update configuration schema

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#562]
We need to make a few changes to the commcare config schema

What we call `applicationName` in our credential is what commcare calls a `domain`. We should update our configuration schema and code to match this.

This is a breaking change. We should not support the legacy applicationName unless someone comes up with a really good reason.

Also,  `appId` and `name`  should be made optional properties.

Finally, we've recently formally introduced a new property `apiKey`, which can be used in place of a password. This should be added to the schema.

A clear changeset needs to document all these changes.

**Comment by aleksa-krolls** [comment]
@hunterachieng moved to Client Backlog

**Comment by aleksa-krolls** [comment]
@hunterachieng moved to Client Backlog

**Comment by hunterachieng** [comment]
@aleksa-krolls  I am still adding more test cases on #528 issue and might get to this later in the evening

**Comment by aleksa-krolls** [comment]
@hunterachieng thanks for update, but I am going to include in next week's sprint since it sounds like there is some work to wrap up :)

**Comment by hunterachieng** [comment]
@aleksa-krolls  I have moved this to code review. A PR is open and added @josephjclark  as a reviewer

**Comment by hunterachieng** [comment]
@aleksa-krolls  this has been merged
