### ISSUE TITLE
`http` Authorisation: Standardise Bearer Token and/or digest implementation

### ISSUE THREAD

**Issue by grayey** [OpenFn/adaptors#58]
Following on issue OpenFn/language-http#36 , we should provide a clean way for users to make use of bearer tokens and/or digest auth.

**Comment by mtuchi** [comment]
@grayey 
Closing this issue since the adaptor already supports `Bearer Token` and `Basic Auth` Authorisation there is not much clarity on why we need to implement `Digest Auth`.
Feel free to reopen this issue if you think there is a need for it and why we need it
