### ISSUE TITLE
top 5: audit src, docs & examples

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#586]
## Request 
[See here](https://www.google.com/url?q=https://docs.google.com/spreadsheets/d/1EsnnFrY8vwRtm4-brcAJ14TQBKHULBFLiNm7kxHG9qk/edit%23gid%3D0&sa=D&source=calendar&ust=1717102064246521&usg=AOvVaw3bHSDo985b2uF3GFb4ccZx) for list of top 5 adaptors we have decided to target improving first. To help us figure out next steps, can you please spend a couple of hours this week to (1) complete the following audit tasks and then (2) create new Github issues for any action items you decided? 

We will then meet next week to go through and prioritize the adaptors issues with Joe and Ayodele. 

To check: 
- [ ] Review the adaptor `src` code to see if there are any anti-patterns or signatures that need to be updated
- [ ] Do all top 5 adaptors have generic get/post/put helpers implemented that use `http`? 
- [ ] Do any examples need to be adjusted to showcase job-writing best practice or to help users more easily implement? 
- [ ] Updates or improvements to the adaptor's function docs?
- [ ] Updates or improvements to the configuration schema? 
- [ ] anything else? 

## Toggl
adaptors

**Comment by aleksa-krolls** [comment]
@mtuchi once video content is wrapped up, we can then start moving on to adaptors examples... but pls make sure to finish up the video issues first before starting here! :)

**Comment by aleksa-krolls** [comment]
Hey @mtuchi I'm not sure how this wrapped up last week... pls leave EOD updates to help me plan! So I'm going to assume that this is done - moving to review.

**Comment by mtuchi** [comment]
Top 5 audit issues 
- https://github.com/OpenFn/adaptors/issues/600
- https://github.com/OpenFn/adaptors/issues/592
- https://github.com/OpenFn/adaptors/issues/597
- https://github.com/OpenFn/adaptors/issues/598
- https://github.com/OpenFn/adaptors/issues/599
