### ISSUE TITLE
http: `errors` object is empty although api returns verbose response

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#624]
## Issue
I'm running this [postPatient.js](https://github.com/OpenFn/jembi-hackathon/blob/main/workflows/jobs/postPatient.js) job against [this sample payload](https://github.com/OpenFn/jembi-hackathon/blob/main/sampleData/patientFail.json) using the latest version of the http adaptor. 
```
post("Patient", {body: state.data,  
 headers: {'content-type': 'application/json'}, 
 parseAs: 'json',
 })
 ```

In app, in the `Log` I see a very verbose and helpful response. In my next workflow step, I would like to map some of these error details (e.g., `resourceType`, `issue`, `meta`) to a postgresql database to keep an external log of errors faced when migrating data to my fhir app. 
<img width="468" alt="Screenshot 2024-06-13 at 1 46 21 PM" src="https://github.com/OpenFn/adaptors/assets/16758106/17c41472-cb12-4644-b356-c18290d7f677">

However, in `Output` this response is _not_ captured in the `errors` object, which is left blank. 
<img width="465" alt="Screenshot 2024-06-13 at 1 45 22 PM" src="https://github.com/OpenFn/adaptors/assets/16758106/e6805527-094b-409a-a8fa-214a9af47045">

Ideally `errors` should show me as much as possible from the API response! 

See example run failure on app.openfn.org: https://app.openfn.org/projects/d52bd48e-451b-4a92-9aad-e7c62a7f0923/w/79930c19-1ce1-4144-82ab-e10d7652e2b5?a=b827f1ff-5723-45a1-aee8-9485afaffcac&m=expand&s=a3b64302-94f1-4cb5-9490-ba87eb6dd6c6#output

## workaround
The below job using `(errors: { 400: false }` allows us to add API response from failed http request to our final state. 
```
post("Patient", {body: state.data,  
 headers: {'content-type': 'application/json'}, 
 errors: { 400: false }, 	
 parseAs: 'json',
 }, state => {
  //console.log('response ::', JSON.stringify(state.response, null,2));
  state.data.response = state.response; 
  return state; 
 }
 ```

**Comment by aleksa-krolls** [comment]
hey @josephjclark - this is the http error issue we discussed today [on slack](https://www.google.com/url?q=https://openfn.slack.com/archives/C017ELVRSM8/p1718272769594519?thread_ts%3D1718271568.274259%26cid%3DC017ELVRSM8&sa=D&source=calendar&ust=1718706961339906&usg=AOvVaw0XGnFDAHiblDIDaXDeyLWc). Assign back to me if you want Hunter/Mtuchi to work on this next week.

**Comment by josephjclark** [comment]
Hey somehow I only just saw this! This is actually a core issue, but I'll be fixing it in kit soon (I've crosslinked the issue)
