### ISSUE TITLE
`npm`  Investigate `@openfn/language-cartoddb` 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#626]
We had a little incident this afternoon and managed to unpublish cartodb. Whoops.

We only meant to remove one release (a test release that I put out for #625 ). I knew I should have made a new test adaptor.

**Comment by josephjclark** [comment]
I've tried to republish the latest release from main but hit this error:
```
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/@openfn%2flanguage-cartodb - Cannot publish over previously published version "0.3.0".
```
This suggests that 0.3.0 is still published and maybe we're seeing some error on npm here.

**Comment by josephjclark** [comment]
Well I've managed to republish a new 0.4.0 version so there is at least something available on npm right now.

I think the history has gotten trashed somehow, perhaps because  we removed the `@latest` tag. Unsure.

**Comment by josephjclark** [comment]
Closing as a wont fix. I think we lost the history but it's fine, the adaptor is available and I think its unused
