### ISSUE TITLE
FHIR Redesign

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#629]
I want to totally overhaul the FHIR adaptor API.

The implementation should use the common http helpers.

I am not a FHIR expert and would appreciate any insights.

What I'm looking for is:
* A clean and consistent base HTTP API
* A set of clean, consistent and helpful high-level functions which map to FHIR verbs (read, create, update,search).

## High level Notes

Why are we doing this, aside from the need to migrate onto new HTTP?

* The FHIR adaptor need a clean separation between the HTTP helpers (`post`) and higher level helper (`create`).
* We've rushed in some changes to support `post` but it's a really janky little release
* The semantic and behaviours of the 3.2.0 docs are not clear. For example:
*  * `create` takes a params object, which is mostly a FHIR data structure. Except it also supports some http stuff, like headers
* * `get` takes a `query` object of query params, which is encoded into the URL. But you can also pass headers into the query, so it's sort of a hybrid of HTTP options and query parameters
* For some reason `request`, which is really an internal helper, is publicly documented and looks broken as heck
* Correct me if I'm wrong, but FHIR supports JSON, XML and RDF data. I think this adaptor should basically be hard coded to always take and return JSON. No string formats allowed. If anyone ever wants to use XML or RDF (and why would you?), we'll provided automatic parsing

Some notes on the new design:
* `params` strictly means "an object of FHIR  parameters`, which will be appended to the URL. Every key in a params object must map to the FHIR spec.
* `options` strictly means "an object of optional flags to control the adaptor's behaviour"

## Public Interface

This is the public interface and docs to the function, as users will see on docs.openfn.org. The implementation needs to match this EXACTLY.

All these  are operation factories
```
/**
 * Options provided to a HTTP request
 * @typedef {Object} RequestOptions
 * @property {boolean=true} throwOnError - Set to false to prevent the function throwing for statusCodes greater than 400
 * @property {object} headers - Object of headers to append to the request
 * @property {object} body - JSON payload to attach to the request
 * @property {object} query - Query parameters for the request. Will be encoded into the URL
 */
// Note: parseAs is deliberately excluded here - assume everything is json

/**
 * Send a generic HTTP request to the server
 * @param {string} method - The HTTP method to be used for the request. It defaults to 'GET' if not
 * @param {string} path - The resource path that the request is being made to
 * @param {RequestOptions} [options] - An object containing any additional parameters to be sent with the request, such
 * as query parameters or request body data.
 * @param {string} path - The resource path that the request is being made to.
 * @returns {Operation}
 */
export const request =
  async (method, path, options = {}, callback) =>
  state => ({
    ...state,
    data,
    response,
  });

/**
 * Send a HTTP POST request
 * @public
 * @function
 * @example
 * post("Bundle",{
 *   "resourceType": "Bundle"
 * })
 * @param {string} path - Path to resource
 * @param {object} data - JSON data to append to the POST body
 * @param {RequestOptions} options - Additional options for the request
 * @param {function} callback - (Optional) callback function
 * @returns {Operation}
 */
export const post = (path, data, options, callback) => state => ({
  ...state,
  data,
  response,
});

/**
 * Send a HTTP GET request
 * @public
 * @function
 * @example <caption>Get Patient from FHIR</caption>
 * get('Patient');
 * @example <caption>Get Claim from FHIR with optional query</caption>
 * get("Claim", { _include: "Claim:patient", _sort: "-_lastUpdated", _count: 200 })
 * @param {string} path - Path to resource
 * @param {object} params - Parameters to encode into the URL query
 * @param {RequestOptions} options - Options to control the request
 * @param {function} callback - (Optional) callback function
 * @returns {Operation}
 */
export const get = (path, params, options, callback) => state => ({
  ...state,
  data,
  response,
});


/**
 * Creates a resource in a destination system using a POST request
 * @public
 * @function
 * @example
 * create("Patient",{ ... })
 * @param {string} resource - The resource type to create
 * @param {object} resource - The resource to create
 * @param {object} params - FHIR parameters to control and configure resource creation
 * @param {function} callback - (Optional) callback function
 * @returns {Operation}
 */
// NOTE: the signature takes type and data, and we should post { resourceType, resource } to the server
export const create = (resource, resource, params, callback) = (state) => ({
  ...state,
  data,
  response,
});

/**
 * Creates a transactionBundle for HAPI FHIR
 * @public
 * @example
 * createTransactionBundle([
 *     {
 *       fullUrl: "https://hapi.fhir.org/baseR4/Patient/592442",
 *       resource: {
 *         resourceType: "Patient",
 *         id: "592442",
 *         name: [{ given: "Caleb", family: "Cushing" }],
 *       },
 *       request: {
 *         method: "POST",
 *         url: "Patient",
 *       },
 *     },
 *   ]);
 * @function
 * @param {array} entries - array of transactiions
 * @param {object} params - data to create the new transaction
 * @param {function} callback - (Optional) callback function
 * @returns {Operation}
 */
export const createTransactionBundle = (entries, params, callback) = (state) => ({
  ...state,
  data
})


/**
 * Get Claim in a FHIR system
 * @public
 * @function
 * @example
 * getClaim({ _include: "Claim:patient", _sort: "-_lastUpdated", _count: 200 });
 * @param {string} claimId - claim id
 * @param {object} params - query parameters
 * @param {function} callback - callback function
 * @returns {Operation}
 */
export const getClaim = (claimId, params, callback = s => s)  => (state) => ({
  ...state,
  data
})
```

## Implementation Notes

* We should not override and export `execute`.
* The HTTP  verbs should all be light wrappers around the request operation
* The `request` operation should call out to utils.request, which uses the common http helper
* I propose we assume that all bodies are JSON, so we should always try to JSON.parse a response regardless of content type.  If the parse fails we return plan text. We can later suppor XML and RDF data if someone really really wants it
* All underlying HTTP methods should be logged to the control (including for high level wrappers like `create`)

## A Question

In FHIR, all parameters seem tostart with an underscore, ie, `_format`,  `_sort`, `_count`. Is that to distinguish systme fields from data fields? Can we look at removing the leading underscore in a params object?

**Comment by josephjclark** [comment]
I think FHIR uses parameters to mean "optional information encoded in the URL query to control the request". We should honour this. Anywhere we  accept/forward a FHIR parameter should be in a `params` object

We should use `options` to control optional openfn stuff or the low-level request so `headers`, `throwOnError` flags, etc

**Comment by aleksa-krolls** [comment]
@josephjclark I'm on board with defaulting to JSON for the OpenFn adaptor, but this should be well documented. I'm going to add this issue to Hunter's backlog, because I'm expecting uptake on this adaptor - but we should take time to do this one right. Therefore, please help her with the estimate, and let me know if there are any design points you want to chat through as I've been getting fairly familiar with FHIR in the last month.

**Comment by aleksa-krolls** [comment]
@mtuchi can you pls sync with Joe and pick this up this week? We'll need it for the upcoming Jembi project.  

You can use the below creds for test FHIR endpoints. 

HAPI FHIR
- Base URL: http://hapi.fhir.org/baseR4
- Docs: https://hapi.fhir.org/
- Swagger: https://hapi.fhir.org/baseR4/swagger-ui/


If this^ is down, you can try this [Firely Server](https://server.fire.ly/) site: 
- baseURL: https://server.fire.ly/
- API Path `R4` (for version for... if using postman, I know sending a POST to `https://server.fire.ly/R4/Patient` works

**Comment by mtuchi** [comment]
@josephjclark should we remove support for callback in this ticket ?

**Comment by josephjclark** [comment]
@mtuchi I'm gonna say "no", just because I need to add runtime support for .then(), and this work will be done before I can do that.

So keep callbacks for now. Don't add any new ones though
