### ISSUE TITLE
`mssql`: Credential investigate on lightning 

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#630]
### Description 

If you use the `mssql` credential on lightning it enforce you to use `encrypt` and `trusted certificate`. I need to investigate further why this is happening.

**Comment by aleksa-krolls** [comment]
From Mtuchi: I think the bug i am experiencing using mssql credential was suppose to be fixed with this PR https://github.com/OpenFn/adaptors/pull/512,  But something is still not right with mssql credential

**Comment by mtuchi** [comment]
This PR https://github.com/OpenFn/adaptors/pull/512 was for solving the credential issue

**Comment by mtuchi** [comment]
Okay after a throughly investigation i discovered two things 
1. The configuration-schema for mssql adaptor is missing a title for `port` property 
2. The default values in the configuration-schema are not picked up by lightning on credential form. This is why i was getting an error saying `Server requires encryption, set 'encrypt' config option to true.` while i know for a fact that mssql adaptor set the `encrypt` option to `true` by default
