### ISSUE TITLE
CHT adaptor for pulling (community health toolkit)

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/adaptors#634]
Right now we integrate with the community health toolkit by having CHT push to OpenFn using webhooks. We should add an adaptor that pulls as well.

To start, this adaptor should: 
1. handle authentication 
2. include a generic GET helper so we can get any resource
3. include a generic POST so we can create any resource
4. include a generic PUT so we can update any resource

_Later_ we can consider adding more abstraction and specific helper functions. For now, the generic requests would be a great start. (FYI I think Hunter recently worked on a template for these generic http requests when she was working on Satusehat adaptor with Joe - maybe sync with her if you're not sure what next steps are.)

## Demo account 
See LP `CHT Demo Project` for login information. You'll find that there is already some dummy data in there.  

## Resources
https://docs.communityhealthtoolkit.org/apps/reference/api/

![rectangle](https://github.com/OpenFn/adaptors/assets/8732845/f7f592c5-985b-4458-9e6b-c2b5fb9ac03e)
![square](https://github.com/OpenFn/adaptors/assets/8732845/d5f1a887-51f2-4c5e-bf90-5bc5b488dbad)

**Comment by aleksa-krolls** [comment]
Noted @taylordowns2000 - will slot in the 2/3rd week along with OpenLMIS

**Comment by mtuchi** [comment]
I won't be able to work on this issue today, let's promote this to next week sprint

**Comment by aleksa-krolls** [comment]
hey @mtuchi - we're going to give this issue to Hunter because of some shifts in HIH timelines

@hunterachieng pls watch [this vide](https://www.youtube.com/watch?v=Gxf0xNvZPG8&ab_channel=TechChange) and check out the [CHT website](https://communityhealthtoolkit.org/) for background. Also please book time on my calendar for Monday afternoon to get more context on this new app cc @AishaHassen

**Comment by mtuchi** [comment]
Okay sounds good 👍🏽

**Comment by hunterachieng** [comment]
@aleksa-krolls  I have boked a meeting

**Comment by aleksa-krolls** [comment]
If we want to test this later...
1. CHT/Medic team _might_ grant us access to a sandbox cloud environment
2. _Or_ we could consider setting up our own CHT instance locally: https://docs.communityhealthtoolkit.org/hosting/4.x/app-developer/
