### ISSUE TITLE
salesforce: autofetch is broken

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#644]
The autofetch feature on the salesforce query sort of works but also not really.

This PR #478 introduced a few regressions:

* Referneces is nested, so you have to do `[0][0]`
* The adaptor pushes responses into references, not recerds, So the data isn't really even accurate

Basically autofetch needs to push the RECORDS into a single flat results array

Not to mention that the code is a bit quirky, to say the least.

I'd also ask whether callback should be triggered per batch, or at the end result. I think that when you're talking about a batch processing API it make sense to chunkup the callback or else you're likely to hit a problem downstream. Maybe this is an option. This is something that comes up on many APIs so I'd want to think carefully about what we do here.

**Comment by josephjclark** [comment]
And there are no unit tests on any of this functionality

**Comment by josephjclark** [comment]
The other metadata is not useful when using autofetch. We'll use that stuff internally but there's no point feeding it back to the user.

**Comment by aleksa-krolls** [comment]
Agreed with Joe's comment.
