### ISSUE TITLE
`primero` Fetching referrals improvements

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#661]
### Description 

When fetching cases referrals during job execution the logs doesn't mention were fetching referrals, This might seem like the workflow is stuck while in reality we are fetching case referrals 

### Request in few words 
- Add a log to show we are fetching referrals for the retrieved cases
- Improve documentation for `withReferrals` option

**Comment by josephjclark** [comment]
Yeah, the documentation right now is actually wrong!

We need to correct the docs and add an example with referrals. We should also add a note that referrals generates one request per case and may impact performance.

I think we should fix this immediately while we're looking at it. It won't take long.

**Comment by josephjclark** [comment]
It is annoying that primero seems to have an id to bulk-insert referrals for a number of cases; but has no API to bulk-fetch referrals for a number of cases. Oh well.

**Comment by aleksa-krolls** [comment]
hey @mtuchi you can use the demo cred in LP `Primero V2 Cambodia Demo (api_user)` to test this, and let Aissatou know if you need any assistance testing, creating test data, etc.

**Comment by mtuchi** [comment]
Thanks AK, noted 

> hey @mtuchi you can use the demo cred in LP `Primero V2 Cambodia Demo (api_user)` to test this, and let Aissatou know if you need any assistance testing, creating test data, etc.
