### ISSUE TITLE
salesforce: update API

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#662]
New API design for salesforce, including adding `composeNextState` and removing old code.

## Delivery Plan

We should break this down into three parts:

* Remove old/unused functions, fix tests
* Use composeNextState and fix state.references, update tests
* Update API to new signatures, with basic docs changes

Each part should be treated like its own story. It should have its own PR which is reviewed and merged into an epic branch called `epic/salesforce`.

## Overview

All functions should use `composeNextState` and write to `state.data`.

`references` behaviour should be preserved, but `state.data` should be the primary usage from now on.

We should probably go on and fix #509 here because we're going to be working so close to that problem.

Only basic documentation is included in this issue. We'll do a deep dive on docs later.

We are going to be bold and REMOVE callbacks entirely from the API :scream: This may result in worse performance for this adaptor version on v1, but I think that's acceptable. And `then()` support, which is coming super soon, will empower this adaptor on v2.

It makes sense to use the new expandReferences API, but that's not technically part of the issue.

Note that the HTTP helpers (`request`, `get`, `post`) should use `connection.request`. Docs should make it super clear that these helpers only call _salesforce_ APIs. Later, we will add a generic HTTP API with common (see #668)

This work should only have minimal unit tests. We'll do a deep dive on tests in #666 

Errors should be thrown, not caught and logged , unless there is any specific messaging that can be added 

## API

```
bulkQuery(query, options)

bulk(operation, sObjectName, records, options)

create(sObjectName, records) // use records instead of attrs. Default to batch.

describe(sObjectName)

describeAll()

destroy(sObjectName, ids, options) // rename attrs (which is wrong) to ids

insert(sObjectName, records)

query(soql, options)

request(url, options)

get(url, options)

post(url, data, options)

retrieve(sObjectName, id)

update(sObjectName, records)

upsert(sObjectName, externalId, records)

toUTF8(as-is)

fnIf() // exported out of common
```
## Code Removal

To be clear, the list above is the whole API. The following functions should all be **removed**.

   - `cleanupState()`
   - `steps()`
   - `reference()`
   - `createIf()`, `upsertIf()` 
   - describeAll()  maybe?
   - remove axios 
   - remove beta from common
   - remove relationship

**Comment by josephjclark** [comment]
This may fix #644

**Comment by mtuchi** [comment]
Just a thought exercises 🧠 , Should we keep exporting the following function from `@openfn/language-common` 🤔 ?
- dataPath,
- dataValue,
- field,
- fields,
- referencePath
- source,
- sourceValue,

**Comment by mtuchi** [comment]
How important is `export const relationship =(relationshipName, externalId, dataSource)=>({ [externalId]: dataSource })` ? 🤔 
Could this be a fix for `{externald.abc: '123'}` vs `{externalId: { abc: '123'}}`

**Comment by mtuchi** [comment]
Good start today, i have done lots of cleanup but still work in progress. I will keep at it tomorrow

**Comment by mtuchi** [comment]
Okay today went by so quick,  i haven't done much in this issue but i have manage to start clearing the callbacks in each function. I need another programming block tomorrow tidy this up

**Comment by mtuchi** [comment]
This issue is technically done, I need to create a changeset and update the PR description #682 

Notes For Next Step:
- [ ] Create a changeset file that has a list of what has been changed, removed, added
- [ ] Update the PR notes for Joe

cc @aleksa-krolls

**Comment by josephjclark** [comment]
@mtuchi please keep the changeset really BRIEF! I would rather ask you to add detail than to remove it

[commcare 2.0](https://docs.openfn.org/adaptors/packages/commcare-changelog#200) is a really good model for the right level of detail

**Comment by mtuchi** [comment]
#682 is ready for review 

- [x]  Create a changeset file that has a list of what has been changed, removed, added
- [x]  Update the PR notes for Joe
