### ISSUE TITLE
`openLMIS` Add OAuth support and generic helpers (get, post, put)

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#670]
### Description 
To start, this adaptor should handle authentication via OAuth and support the following operation 

- [x] include a generic GET helper so we can get any resource
- [x]  include a generic POST so we can create any resource
- [x]  include a generic PUT so we can update any resource

**Demo Server Credentials:** 
URL: https://demo-v3.openlmis.org/#!/home
username: **administrator**
password: **password**

OpenLMIS API requests are authenticated by an OAuth2 access token passed as a query parameter. See a sample API request below: 

```
GET /api/reports/templates/requisitions/{id}?access_token=
9a556033-ed13-4dde-9561-158469d15134

URI Parameters
id: required (string)

Query Parameters
access_token: required (string)
OAuth2 access token

```

Link to test OAuth2 token here: https://github.com/OpenLMIS/openlmis-auth/blob/master/src/main/resources/db/demo-data/auth.api_keys.csv

**Comment by mtuchi** [comment]
@christad92 i get the access_token and also i can't login to the https://demo-v3.openlmis.org/#!/home with the given credential

**Comment by mtuchi** [comment]
API documentations
- [API Console](https://test.openlmis.org/auth/docs/#!/default/post_api_oauth_token)
- [API Docs 3.0.2](https://docs.openlmis.org/en/rel-3.0.2/api/index.html)
- [Auth Service](https://github.com/OpenLMIS/openlmis-auth/blob/master/DESIGN.md#auth-service-design)

**Comment by mtuchi** [comment]
I have made good progress on this issue,  See #675 But i am missing unit test which i think it's crucial to have
I have skipped the unit test for now but i will implement them before requesting review from Joe

**Comment by josephjclark** [comment]
@mtuchi I can't log into the demo server either - any tips?

**Comment by mtuchi** [comment]
Ooh yeah @josephjclark i was testing using `https://test.openlmis.org` i forgotten to update the issue 🤦🏽 

Since the adaptor is already released can we close this issue now ?
