### ISSUE TITLE
`redis` changes to `scan()`

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/adaptors#710]
#### Description
* scan needs to iterate the whole database (and we need to document this!)
* scan should not take cursor parameters (it's too hard to loop in job code, so let's just do it in the adaptor function).
* We can take `count` as an argument in case users want bigger "pages". This allows for some optimization.
* Type should not have a default value
* We should support the `json` type and map it to the redis internal type

I'd love a good unit test on the updated scan but that depends a bit on how easy it is to mock out the scan API. Maybe we can mock the iterator to return three "pages" of results?

Again, we'll likely evolve and improve this API in future

Ref: #686

**Comment by josephjclark** [comment]
Will be released in 1.1.0
