### ISSUE TITLE
axios: bump version to 0.28

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#727]
I'd like to bump axios versions to 0.28 across the repo. This will clear out some security notifications (it won't of course affect production releases).

The affected adaptors would be:

```
dhis2
godata
mailchimp
openfn
progres
rapidpro
salesforce
```

Some big tickets there. We can ignore salesforce as axios will be dropped soon anyway.

The 0.x changelog does report some breaking changes: https://github.com/axios/axios/blob/main/CHANGELOG.md

They look subtle. There's some stuff around formdata which makes me nervous.

I think the thing to do is to bump axios, and put a warning in the patch notes that the axios version changed. If any problems are introduced, we'll just have to fix them on demand.

**Comment by josephjclark** [comment]
Axios 0.28.0 breaks `paramSerializer`, which breaks DHIS2.

I don't know what else broke, but I am very grateful to DHIS2's unit tests :pray:

**Comment by mtuchi** [comment]
I wish we can remove all `axios` export first. Eg in salesforce then we can slowly plan a refactor for adaptor that uses axios in their functions

**Comment by mtuchi** [comment]
I have updated axios to latest version `1.7.7.` See #770

**Comment by aleksa-krolls** [comment]
hey @mtuchi @josephjclark can we close this out?

**Comment by mtuchi** [comment]
@aleksa-krolls this is done, let me close it
