### ISSUE TITLE
http: dies on platform if no credential

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/adaptors#733]
The http adaptor does this:
```
export function addBasicAuth(configuration = {}, headers) {
  const { username, password } = configuration;
  if (username && password) {
    Object.assign(headers, makeBasicAuthHeader(username, password));
  }
}
```

(probably other adaptors too)

This blows up on v1 if there's no credential, because v1 passes`null` as the credential. And `null` is a _value_, it won't trigger the default.

While we're still supporting v1, we need to be careful about defaulting the `configuration` object across our adaptors.

we should really fix this in http because `latest` will be forever broken on v1, which isn't so good

**Comment by mtuchi** [comment]
@josephjclark Does this still need fixing ?, I am seeing a much better error on `http@v6.4.4` [current latest version] when running a simple job

Eg: 
```get('mama')```

![Image](https://github.com/user-attachments/assets/1e7998ea-1f25-4411-a704-19f4c00d59e2)

**Comment by aleksa-krolls** [comment]
@mtuchi was something done in a recent release to address this? 

Bc in `v6.4.3` or `v.6.4.2` it was causing the workflow to crash if no `baseUrl` was defined _or_ if credential was not added at all to the job (no `configuration` values present).

**Comment by mtuchi** [comment]
From our pairing session with @aleksa-krolls, Tested on v2 a simple job without credentials using http adaptor
 `v6.2.0` to `6.4.4` it works as expected.

```js
get('/jokes/random')
get('https://api.openconceptlab.org/mappings/')
```

**Comment by josephjclark** [comment]
We know it works on  v2, the problem is only seen on v1. It doesn't matter that we get a nice error - the problem is it shouldn't error at all.

So yes, this still needs fixing unfortunately

**Comment by mtuchi** [comment]
@josephjclark 
But isn't `INVALID_URL` the expected error because you don't have any baseUrl if your making this request `get('/jokes/random')` ?

**Comment by josephjclark** [comment]
Hmm. It's a badly written issue and I only barely remember it. But I think the problem is that `get('https://api.openconceptlab.org/mappings/')` fails on v1 if there's no credential. It's the thing about the credential being null. You could probably reproduce that in a unit test. Or using the CLI, maybe set `state.configuration` to null. That'll probably cause a similar exception.

`get('mama')` is indeed an INVALID_URL if there's no baseURL in the credential, but I don't think that's what we're talking about. We should handle that case better by saying "You passed a relative URL but didn't set baseURL" or something.

**Comment by aleksa-krolls** [comment]
Ah I agree with Joe @mtuchi ... didn't think about this use case, but some jobs do _not_ require authentication and no credential... so that should be allowed.

**Comment by mtuchi** [comment]
**EOD Update**
I have improved the error logs in http adaptor when `baseUrl` is not set and the relative url is provided. And also if `baseUrl` is not set and the url is not provided

**Comment by josephjclark** [comment]
Thanks @mtuchi, that's cool, but that PR doesn't fix the actual issue here.

You need to change:

```
export function addBasicAuth(configuration = {}, headers) {
  const { username, password } = configuration;
  //  ...
}
```

To this (or some equivalent:
```
export function addBasicAuth(configuration, headers) {
  const { username, password } = configuration ?? {};
  //  ...
}
```

To understand what's happening, try this test in `node` or your browser devtools:
```
function fn(x = {}) {
  return x
}

console.log(fn(1)) // returns 1
console.log(fn(undefined)) // returns {}
console.log(fn(null)) // returns null! 🤯

```

**Comment by mtuchi** [comment]
@josephjclark i have updated the addAuth in `Utils.js` to use `const { username, password, access_token} = configuration ?? {};` But something to note, I have manage to reproduce the bug in `v6.1.0`
![Image](https://github.com/user-attachments/assets/c02dce09-df67-45ad-8381-e4b3a7c332b5)

But in `v6.4.4` it's working as expected without credential 
![Image](https://github.com/user-attachments/assets/b6b83c82-ce19-4227-90b8-111281a65e37)
