### ISSUE TITLE
Replace vulnerable versions of `flat`

### ISSUE THREAD

**Issue by rorymckinley** [OpenFn/adaptors#746]
Versions of the `flat` package prior to 5.0.1 are vulnerable to [prototype pollution](https://github.com/advisories/GHSA-2j2x-2gpw-g8fm). Luckily the vulnerable versions of `flat` are only present in devDependencies and every case is introduced as a dependency of `mocha`, so it should hopefully be as simple as an update of `mocha`.

The following is a list of packages that contain the vulnerable version as a dev dependency:

```
@openfn/language-asana
@openfn/language-beyonic
@openfn/language-cartodb
@openfn/language-dhis2
@openfn/language-godata
@openfn/language-kobotoolbox
@openfn/language-mailchimp
@openfn/language-mysql
@openfn/language-ocl
@openfn/language-postgresql
@openfn/language-primero
@openfn/language-rapidpro
@openfn/language-salesforce
@openfn/language-sftp
@openfn/language-twilio
@openfn/language-zoho
```

**Comment by aleksa-krolls** [comment]
hey @mtuchi @josephjclark what's going on here?

**Comment by mtuchi** [comment]
@aleksa-krolls this is done let me close it
