### ISSUE TITLE
commcare: Create a generic request function

### ISSUE THREAD

**Issue by hunterachieng** [OpenFn/adaptors#751]
### Background, context, and business value
Create a generic `request` function in the commcare adaptor

### The specific request, in as few words as possible
We currently do not have a common `request` function which would allow us to implement more features api calls using `commcare`

**Comment by aleksa-krolls** [comment]
@hunterachieng as discussed, please implement this in the adaptor so we can send generic GET/POST/PUT requests. This will be good to generally implement, as well as unblock us on HIH.

**Comment by hunterachieng** [comment]
We have created 2 functions, `request` for normal json body requests and `bulk` for both `submitxls` and `lookup-table` updates

**Comment by aleksa-krolls** [comment]
hey @hunterachieng can we close this out?
