### ISSUE TITLE
satusehat: access token refresh not working

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#752]
[See example run](https://app.openfn.org/projects/2fedca61-bb42-4e65-a908-7a60f1b25c1e/w/18b59222-b853-4777-9693-cf4e62485402?v=2&a=9f1b4570-f44a-454f-9ae0-1a8f661942fe&m=expand&s=733ef4b5-b6a3-46c7-80a2-cb081d5a3818#log) that fails on app... but the same request is succeeding on Postman. 
```
AdaptorError: POST to https://api-satusehat-stg.dto.kemkes.go.id/oauth2/v1/accesstoken returned 403: Forbidden
```

Credential: See LP `HIH ASRI SATUSEHAT creds`

**Comment by josephjclark** [comment]
This turns out to be a firewalling issue: using the same credential from an Indonesian network (ie a VPN) works just fine.
