### ISSUE TITLE
docs on how to use the adaptor "template" to create your own adaptor

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#774]
We want to start engaging more developers outside of OpenFn to build adaptors... will be a nice way to grow open source contributions. 

I understand that we now have an adaptor "template" for a basic adaptor that handles authentication and supports generic http requests. 

Can you please draft some documentation (designed for outside devs who want to build their own adaptors) explaining what this template is and how to use it? 

[See here](https://github.com/OpenFn/adaptors?tab=readme-ov-file#contributing) for existing docs. Please expand these and/or create a separate docs page dedicated to using the `template` adaptor (whichever you think is best). Assign the PR to me whenever ready!

**Comment by josephjclark** [comment]
Aah sorry @aleksa-krolls I said I'd do this and completely forgot :(

The monorepo readme contains a tutorial that Amber (former product manager) wrote, so its well over a year old by now, and many things have changed (including the new generator).

I think we should remove all that and add a really short, simple guide using the template

For the record I really think this stuff should be in the repo wiki https://github.com/OpenFn/adaptors/wiki. We can always link to wiki docs from the readme.

**Comment by aleksa-krolls** [comment]
@hunterachieng when you start on this, pls note Joe's comment above --> let's add this to the repo wiki

**Comment by aleksa-krolls** [comment]
hey @josephjclark - [see here](https://docs.google.com/document/d/1b_WrC7Ws3HJxxd5k9cwTS5r9aky6ce7dMP5PAxp7IRg/edit#heading=h.tnfwp05673yo) for @hunterachieng 's first draft. Let's discuss next steps when we sync later today, bc I just had a client email me saying they want to build their own Gmail adaptor, so wondering if we can get a v1 of this published soon

**Comment by aleksa-krolls** [comment]
hey @hunterachieng we can mark this as closed, yeah?
