### ISSUE TITLE
commcare: update docs and add examples

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/adaptors#775]
For HIH/Asri we've been using the CommCare adaptor in cool ways - let's document some of these learnings and examples! 
- Please review the docs we have on existing [functions](https://docs.openfn.org/adaptors/packages/commcare-docs) to see if anything needs updating. Also pls make sure all options are documented. 
- Do you have any examples from this Asri project you can add [as new Examples](https://docs.openfn.org/adaptors/library/jobs/auto/Registration-forms-new-case-2023-06-22)? It would be great to see some examples for getting cases, getting and updating lookup tables, etc. 
- The [configuration](https://docs.openfn.org/adaptors/packages/commcare-configuration-schema) does not look up-to-date and is maybe missing UN and password. Can you please review this?

**Comment by hunterachieng** [comment]
@AishaHassen  this is currently under-review by Joe
